README.md
onmt/Dataset.py
onmt/Models.py
onmt/Optim.py
onmt/Translator.py
preprocess.py
train.py
translate.py

Primarily makes a change to variable length encoder, but also makes some small fixes to checkpointing/loading and makes the resumed training more intuitive.

Variable length encoder

---

onmt/Dataset.py
translate.py

Fixed two bugs that caused both training and translation to miss the last batch.
addone() in translate.py adds a None (as EOF) to the end of the input file, which does not break the incrementality of the current design.

fixing the bugs of missing last batch in training and translation

---

train.py

Corrected the final print of the train accuracy to be in the same format as the validation accuracy (percent values instead of [0, 1]).

Corrected the final print of the train accuracy 

---

onmt/Beam.py
onmt/Dict.py
onmt/Optim.py

Preliminary commit to change existing comments to docstrings. This will be followed by lots of additional documentation changes.

Change comments to docstrings

---

onmt/Dataset.py
onmt/Models.py
onmt/Translator.py
onmt/modules/ImageEncoder.py
onmt/modules/__init__.py
preprocess.py
train.py
translate.py

- Adds support for different input types to the system. 
- Cleans up masking in translate
- Implements a simple conv/lstm encoder
- Include preprocessing and translation of image type. 
I tested that I can run the main steps for text models, and I trained a full on image model with good perf.

Im2Text (try 2)

---

onmt/Translator.py
translate.py

loading model to the right place & fix encoding problem

---

README.md

This bash command is not readable:`for l in en de; do for f in data/multi30k/*.$l; do if [[ "$f" != *"test"* ]]; then sed -i "$ d" $f; fi;  done; done`. It is hard to interpret `sed -i "$ d"` as deleting the last line of the file.
Added a comment to help clear this up.

Update README.md with a comment

---

onmt/Models.py

It might be more clear and faster than previous version.

update brnn hidden state from encoder to decoder

---

docs/generate.sh
docs/options/preprocess.md
docs/options/train.md
docs/options/translate.md
onmt/Beam.py
onmt/Loss.py
onmt/Models.py
onmt/Translator.py
onmt/__init__.py
onmt/modules/CopyGenerator.py
onmt/modules/Gate.py
onmt/modules/MultiHeadedAttn.py
onmt/modules/StackedRNN.py
onmt/modules/Transformer.py
onmt/modules/Util.py
onmt/modules/__init__.py
train.py

- Separate out loss, statistics, decoder state, different encoder and decoder modules 
- Add explicit size check assertions to core functions. 
- Simplify beam search to expose core algorithm. 
- Fix dataparallel

Code cleanliness and simplification

---

.gitignore
onmt/Models.py
onmt/modules/GlobalAttention.py
train.py

Added Bahdanau style of attention to v0.2

Bahdanau Attention

---

onmt/modules/GlobalAttention.py

fixed mask size assertion

---

.gitignore

Quality of life (QoL) changes to `.gitignore`

 minor edits to .gitignore

---

train.py

fix issue #106

---

onmt/IO.py

The return of mask may be: src_len x tgt_len.

mask: return src_len x tgt_len

---

train.py

As in https://github.com/OpenNMT/OpenNMT-py/issues/70 for the translator.
I actually tried to continue - without GPU - a training started with GPU. This is probably not a common scenario, but it also handles case where multi-GPU users would like to continue training with another GPU (which may happens more).

Retraining with another device made possible

---

onmt/Models.py

throw error: CopyGenerator dose not support index

share_decoder_embedding conflict with copy_generator

---

train.py

-train_from has been a bit buggy. checking on it.

Fix -train_from options and opt-state

---

onmt/IO.py

@srush Here is the added change to the previous PR #213

Fix dynamic_dict with pickle [also overwrite __setState__]

---

onmt/Beam.py
onmt/Loss.py
onmt/Translator.py

Assure we have at least n_best outputs even if not finished when we hit max_length. Also remove a counter bug.

Fix beam search max_length bug

---

onmt/Translator.py

"-tgt" do not need to replace unk

translate.py Error with both "-tgt" and "-replace_unk"

---

onmt/modules/Transformer.py

@JianyuZhan apparently you are supposed to register buffers like this. Seems to fix issue.

Make mask a buffer.

---

onmt/modules/SRU.py

Hi, it turned out that only changing `RSU` class was enough to fix the bug.

fixed the bug in issue #277

---

onmt/IO.py

Switch to aggressively use iterators to handle some of the memory issues in IO.py

Partial fix for memory issue in IO.py 

---

onmt/IO.py

Added a check whether a line is empty when reading in a corpus during preprocessing. 
#284 #252

preprocess empty lines as empty

---

onmt/modules/SRU.py

I forgot to reshape `grad_last` in `backward`. That is why the weird phenomenon I mentioned before occurred. After fixing it, the loss can drop nicely.

fix an issue and use new SRU which supports ReLU

---

onmt/Trainer.py

fix bug with tgt in truncated decoding

---

onmt/Trainer.py

Minor Fix.
Passing the function the `learning rate` and not the optim object.

[FIX] logging function for crayon

---

onmt/ModelConstructor.py
onmt/Trainer.py
train.py

Two bug fixes

---

onmt/modules/SRU.py

This PR fixes #335,  a Windows compatibility bug.

check_sru_requirement: fix a platform compatibility bug

---

onmt/modules/CopyGenerator.py

As suggested, the loop for replacing 0 values (`<unk>`) in target is inefficient.
This implementation only uses tensor operations and was 10 times faster in my context.

Faster target correction (replacing unk tgt values)

---

onmt/Models.py
onmt/Translator.py
onmt/Utils.py
onmt/modules/GlobalAttention.py
test/test_attention.py
translate.py

Reverts OpenNMT/OpenNMT-py#402

Revert "Fix batch translation"

---

README.md

as suggested in the PR [#398](https://github.com/OpenNMT/OpenNMT-py/pull/398) introducing `embeddings_to_torch.py`

README: mention pretrained embeddings tutorial

---

onmt/Models.py
onmt/Translator.py
onmt/Utils.py
onmt/modules/GlobalAttention.py
test/test_attention.py
translate.py

Reverts OpenNMT/OpenNMT-py#413

Fix batch translation

---

onmt/modules/Conv2Conv.py
onmt/modules/Transformer.py

Two decoder forward interfaces are forgotten in that patch.
Fixes part of #432.

Fix "Fix batch translation"

---

train.py

fix for the experiments reproducibility

fix seed of torchtext

---

docs/generate.sh
docs/source/conf.py
docs/source/onmt.modules.rst
docs/source/onmt.rst
onmt/modules/StructuredAttention.py

(Some more documentation fiddling.)

Reduce the docs that show up on the main page

---

onmt/modules/MultiHeadedAttn.py
onmt/modules/Transformer.py

Applying changes to Transformer based on opennmt-tf #432

Applying changes based on opennmt-tf #432

---

onmt/ModelConstructor.py

train: explicit check when training with share_embeddings and not share_vocab

---

onmt/__init__.py
onmt/translate/Beam.py
onmt/translate/Translator.py
onmt/translate/__init__.py
preprocess.py
translate.py

Fix for an old issue that is quite bad, https://github.com/OpenNMT/OpenNMT-py/issues/338
Additionally, 
- Move the translation files to a submodule for cleanliness. 
- Reorganize some of the translation code for readability.

Fix UNK replacement issues

---

onmt/Loss.py

Two updates of label smoothing:
1. Report true perplexity.
2. Reduce computation cost of mask operation.

Fix incorrect perplexity reported when label smoothing enabled.

---

.travis.yml
CONTRIBUTORS.md
docs/source/conf.py
onmt/ModelConstructor.py
onmt/Models.py
onmt/Optim.py
onmt/Trainer.py
onmt/io/IO.py
onmt/modules/ConvMultiStepAttention.py
onmt/modules/Gate.py
onmt/modules/ImageEncoder.py
onmt/modules/SRU.py
onmt/modules/WeightNorm.py
onmt/modules/__init__.py
onmt/translate/Beam.py
onmt/translate/Translation.py
onmt/translate/Translator.py
onmt/translate/__init__.py
requirements.opt.txt
test/pull_request_chk.sh
test/test_models.py
test/test_preprocess.py
tools/extract_embeddings.py
translate.py

This is a purely cosmetic refactoring of the translation code to try to make things easier to extend and pay off some of the code debt that we are in. 
Additionally transitions us to use the stricter `pep8-naming` style for naming consistency. 
Hopefully this shouldn't have any semantic changes.

 Refactor Translation Code

---

docs/source/index.rst
docs/source/onmt.io.rst
docs/source/onmt.modules.rst
docs/source/quickstart.md
docs/source/refs.bib
onmt/ModelConstructor.py
onmt/Models.py
onmt/io/AudioDataset.py
onmt/io/ImageDataset.py
onmt/io/TextDataset.py
onmt/modules/AudioEncoder.py
onmt/modules/Conv2Conv.py
onmt/modules/ConvMultiStepAttention.py
onmt/modules/CopyGenerator.py
onmt/modules/Embeddings.py
onmt/modules/Gate.py
onmt/modules/ImageEncoder.py
onmt/modules/MultiHeadedAttn.py
onmt/modules/SRU.py
onmt/modules/Transformer.py
onmt/modules/WeightNorm.py
onmt/modules/__init__.py
onmt/translate/Beam.py
onmt/translate/Translation.py
onmt/translate/Translator.py

Finishing up the core docs. 
(Don't think there are any code changes here)

More docs 

---

docs/source/options/train.md
onmt/translate/Translation.py

Just fixing a typo in the variable name :)

Fix #479 (along with a small typo in docs)

---

opts.py
train.py

Fix additional memory allocation during validation.
#476 #301

Fix issue#476, issue#301

---

docs/source/quickstart.md

.. and made minor editorial changes to text

documentation for quickstart tested..

---

onmt/io/AudioDataset.py
onmt/io/ImageDataset.py
onmt/io/TextDataset.py
onmt/translate/Translation.py
requirements.txt
test/test_preprocess.py
train.py
translate.py

Fix torchtext new version compatibility problems.

---

onmt/Loss.py
onmt/Trainer.py
onmt/modules/CopyGenerator.py
opts.py
train.py

Gradient accumulation for large batch size.
[See here.](https://github.com/OpenNMT/OpenNMT-py/pull/293#issuecomment-357180087)

gradient accumulation for large batch size 

---

onmt/Trainer.py
onmt/io/DatasetBase.py
onmt/io/IO.py
onmt/io/TextDataset.py
onmt/modules/CopyGenerator.py
preprocess.py
test/test_preprocess.py
train.py

Reverting seems broken. Looking into it.

Revert "Fix preprocess sharding and implement train side lazy dataset load"

---

onmt/Trainer.py
onmt/io/DatasetBase.py
onmt/io/IO.py
onmt/io/TextDataset.py
onmt/modules/CopyGenerator.py
preprocess.py
test/test_preprocess.py
train.py

Reverts OpenNMT/OpenNMT-py#511

Unrevert "Fix preprocess sharding and implement train side lazy dataset load"

---

onmt/Trainer.py
train.py

- Seemingly the old code only works for one iteration. Change the code so that it reinitializes the iteration each time and passes to train and test.

Fix some more lazy loading bugs

---

onmt/Trainer.py

Bug fix for gradient accumulation.

---

onmt/Trainer.py
onmt/io/IO.py
preprocess.py
train.py

This PR just cleanups preprocess/train code.  No functional change.

Code cleanups

---

onmt/io/DatasetBase.py

We now do lazy load on train side, this method is not needed anymore.

DataBase: remove unused static method

---

.gitignore
onmt/Trainer.py
opts.py
train.py

Embeddings don't load on tensorboard for me, so that is not included in this PR.
The pytorch 0.4 detach support can be taken it out, it was so I could get this running.

Add tensorboard logging during training

---

docs/Makefile
onmt/Models.py
onmt/modules/Conv2Conv.py
onmt/modules/GlobalAttention.py
onmt/modules/Transformer.py
onmt/translate/Translator.py
test/test_attention.py
test/test_models.py

This is a cosmetic PR. We discussed changing a bunch of the names to conform more in line with the literature and more consistent throughout.

Renaming variables in the core Encoder/Decoder.

---

onmt/ModelConstructor.py
onmt/Models.py
opts.py

This PR implements a bridge option that represents an additional linear layer between the last encoder state and the first decoder state.

Adding Bridge option

---

tools/embeddings_to_torch.py

Suggest a fix for: http://forum.opennmt.net/t/error-in-embeddings-to-torch-py-pytorch/1299

Associating vocabularies based on its name

---

onmt/io/TextDataset.py

Reverts OpenNMT/OpenNMT-py#581

Revert "Change batching to a more sensible ordering."

---

onmt/Models.py
onmt/Utils.py

We are currently not updating the input_feed variable in Models.py - means we are not training with input_feed enabled.

Fix input feed

---

onmt/Trainer.py
opts.py
train.py

Fix tensorboard formatting to use tabs and edit tensorboard_logdir argument for run name.

Fix tensorboard formatting to use tabs

---

.travis.yml
onmt/modules/Embeddings.py
onmt/modules/GlobalAttention.py
onmt/modules/MultiHeadedAttn.py
onmt/modules/Transformer.py
onmt/modules/UtilClass.py
onmt/modules/__init__.py

Some micro-optimizations to get some more memory for transformer.

Transformer Memory

---

onmt/Loss.py
onmt/ModelConstructor.py
onmt/Optim.py
onmt/Trainer.py
onmt/io/TextDataset.py
onmt/modules/Embeddings.py
onmt/modules/MultiHeadedAttn.py
onmt/modules/Transformer.py
onmt/modules/UtilClass.py
onmt/translate/Translation.py
onmt/translate/Translator.py
opts.py
train.py
translate.py

We're still a bit slower to converge than TF on small example data, and lagging on big dataset.

Some more transfomer differences with TF version. 

---

onmt/ModelConstructor.py
onmt/Optim.py
opts.py
train.py

Add an explicit option for the xavier_uniform init. Seems to be necessary to replicate transformer.

Add transformer initialization as an option.

---

onmt/modules/Embeddings.py

Need check for count of features when doing feat merge of mlp

---

tools/average_models.py

Compute average between multiple models. I also remove the `optim` part of the model file.
**Usage:** 
```
./tools/average_models.py -m  <model_1> <model_2>  ... <model_n>  -o <output_file>
```
----
* related issue: https://github.com/OpenNMT/OpenNMT-py/issues/514

Model averaging

---

onmt/translate/Beam.py
onmt/translate/Penalties.py

Trigram Penalty

---

docs/source/options/train.md

https://github.com/OpenNMT/OpenNMT-py/issues/652

Clear description of `-share_embeddings` doc

---

translate.py

implemented -attn_debug

---

.travis.yml
README.md
onmt/Loss.py
onmt/Models.py
onmt/Trainer.py
onmt/io/IO.py
onmt/modules/Conv2Conv.py
onmt/modules/ConvMultiStepAttention.py
onmt/modules/Embeddings.py
onmt/modules/ImageEncoder.py
onmt/modules/MultiHeadedAttn.py
onmt/modules/SRU.py
onmt/modules/StructuredAttention.py
onmt/modules/Transformer.py
onmt/modules/UtilClass.py
onmt/modules/WeightNorm.py
onmt/translate/Translator.py
test/test_models.py
test/test_preprocess.py

add retain_graph=True and do conversions to get correct accuracy numbers.

pytorch 0.4

---

onmt/opts.py

Remove brnn_merge

---

onmt/io/IO.py

#723 crash if there's blank line in vocab file

---

.gitignore
onmt/translate/Translator.py

Sorry, going to revert this until we merge the refactoring, and then reinclude.

Revert "Fix : -report_bleu issue"

---

onmt/utils/report_manager.py

It solves https://github.com/OpenNMT/OpenNMT-py/issues/780

Switching back to `tensorboardX`

---

onmt/modules/copy_generator.py
onmt/trainer.py

1. fix None grads:
- as described in https://github.com/Ubiqus/OpenNMT-py/issues/5, more precisely [this comment](https://github.com/Ubiqus/OpenNMT-py/issues/5#issuecomment-395704362) 
- I'm not sure why this error is even raised: there may be a deeper problem that need to be investigated
2. Implicit softmax dimension:
- https://github.com/Ubiqus/OpenNMT-py/commit/04c67bd7eb920b1174655e3f963fb19a424773bc wasn't enough

fix None grads and implicit dimension

---

onmt/translate/translator.py

The new beam search implementation now also supports:
* `-n_best`
* `-replace_unk`
* `-min_length`

Support more decoding options in fast beam search

---

onmt/translate/translation_server.py

- related issue: https://github.com/OpenNMT/OpenNMT-py/issues/819

Use 'self.opt' (namespace) instead of 'opt' (dict)

---

README.md
floyd.yml
floyd_requirements.txt

Hi @srush, here's the [Run on FloydHub](https://docs.floydhub.com/guides/run_on_floydhub_button/) integration.
- Added the button (and the badge) in the README.md
- Added the `floyd.yml` config file to specify the environment
- Added the `floyd_requirements.txt` file to specify the extra-dependency to install in the environment
Looking forward to your feedback :)

Run on FloydHub integration

---

onmt/trainer.py

quick fix of #921 to make it work with pytorch 0.4.1

patch to fix 0.4.1 compatibility

---

tools/embeddings_to_torch.py
tools/extract_embeddings.py

Similar to https://github.com/OpenNMT/OpenNMT-py/blame/e723f2aa70edb6920c0f0fe311b19aff0dcdf552/tools/embeddings_to_torch.py#L20
* fix https://github.com/OpenNMT/OpenNMT-py/issues/812

Fix extract embeddings src/tgt vocabulary

---

onmt/utils/logging.py

* fixes: https://github.com/OpenNMT/OpenNMT-py/issues/893

fix logging to file

---

onmt/tests/rebuild_test_models.sh
onmt/tests/test_models.sh
onmt/trainer.py

#923 did not fix all the issue. (worked in token mode, not on sentence mode)

fix #923 for backward compatibility

---

onmt/train_single.py

fixes #942

---

onmt/translate/translator.py

This PR iterates on #875 to improve the fast beam search correctness and align its output with the non fast path.
* Restructure the code to better handle the last predicted token
* Do not ignore good hypotheses that finish early
Expect a slight impact on translation speed as more work has to be done each time an hypothesis is finished.

Improve fast beam search correctness

---

onmt/opts.py
onmt/train_single.py

I've made some changes to enable true reproducibility based on another project where I had to enable that feature. The changes:
* Fixed the seed for numpy as well (which is used in transformer, p.e.)
* Set the CUDNN backend to deterministic mode, otherwise you may find small variations on each experiment.
* Now the random seed is always set if provided.
* Some typos changed.
Hope it helps.

Properfly fixing the seed to reproduce experiments

---

onmt/utils/distributed.py

Reverts OpenNMT/OpenNMT-py#876

Revert "Set Random Port for Torch Distributed Nccl backend."

---

onmt/opts.py

Fix a typo in opts.py

---

docs/source/Library.md

Update example in docs to match onmt.utils.optimizers.Optimizer parameters.

Method signature fix

---

CHANGELOG.md
onmt/__init__.py
preprocess.py
setup.py

Filenames extensions were trimmed leading to a bug when language was the extension
Cleaning text files after sharding
Bump version 0.4.1

Fix preprocess filenames + cleaning. Bump version 0.4.1

---

onmt/decoders/ensemble.py

This PR updates the ensembling code to account for changed behavior in encoders.

fix bug from changed expectations of encoder output

---

onmt/translate/translator.py

Penalize beams that reached </s>

---

CHANGELOG.md
onmt/__init__.py
onmt/opts.py
preprocess.py
setup.py

+ fix raise error on use of -shuffle at preprocess (not supported)

Bump version

---

onmt/translate/translator.py

Support other input data types in fast beam search

---

onmt/models/model.py

remove useless code

---

onmt/train_single.py
onmt/translate/translator.py
train.py

fix #1026 
fix  #1021 done before #1023

fix gpuid deprecated / #1021 mismatch

---

onmt/decoders/ensemble.py
onmt/translate/translator.py

fix ensemble decoding (copy_attn and fast)

---

onmt/translate/beam.py
onmt/translate/translator.py
onmt/utils/loss.py

Goal is to:
- eliminate all the option list of the Translator Class and pass the full opt/model_opt
- factor the decoder / generator to be used by:
1) translate_batch (now using same dimension order as fat ie batch x beam for tensors)
2) _fast_translate_batch
3) Gold scores retrieval (_score_target)
- fix Gold Scores in copy_attn mode
Ready for review.
Tested in text mode for copy / non-copy
Tests for Image / audio are welcome.

Translator refactor

---

onmt/utils/report_manager.py
preprocess.py

fix preprocess check when using sharding (src length=tgt length was no longer tested)
fix stats report fixing #1039 not being updated

Quick fixes

---

onmt/modules/conv_multi_step_attention.py
onmt/utils/cnn_factory.py

fix a bug introduced by 
https://github.com/OpenNMT/OpenNMT-py/commit/ec2250c3c90c4b03a1aaa718ceb0a857d32d58cc

fix cnn softmax

---

onmt/models/sru.py
onmt/opts.py
onmt/tests/test_models.py
onmt/tests/test_preprocess.py
onmt/train_single.py
onmt/translate/translation_server.py
onmt/translate/translator.py
preprocess.py
requirements.txt
server.py
train.py
translate.py

It's basically what have been done with: https://github.com/OpenNMT/OpenNMT-py/pull/339, I had a hard time merging it, reproducing was in fact far easier.
In addition, I propose to load default opts and overwrite it with checkpoint options when re-training a model. The idea is to allow retraining a model even after some options has been added i.e. adding a new flag won't raise error if a default value for the flag as been set.

Configargparse + using default values (if none set) when retraining

---

docs/source/options/train.md

Added description for option -reset_optim introduced in 6f8ad70

Doc update according ability to reset optimizer

---

onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/modules/copy_generator.py
onmt/modules/multi_headed_attn.py
onmt/translate/beam.py

and rely on the operators broadcasting semantic.

Remove some manual tensor expansions

---

onmt/modules/copy_generator.py

Squeeze is over-eager when the batch size is 1. This should fix the issue.

Fix #1090, dimension issues in copy generator loss

---

onmt/modules/multi_headed_attn.py

remove useless code in transformer decoder cache

---

onmt/translate/translation_server.py

An easy way to protect critical sections of code.
In particular, it protects for calling `run` and `to_cpu` (or `unload`) in the same time. 
(still need some testing tho)

Introduce critical section decorator for translation server

---

onmt/utils/optimizers.py

This is mostly a small factorization work:
* remove optimizer-specific code paths
* harmonize learning rate decay definitions and update

Small optimizer refactoring

---

onmt/opts.py
onmt/utils/__init__.py
onmt/utils/optimizers.py

This is a first step to introduce Adafactor as an Optimizer.
based on this: https://arxiv.org/pdf/1804.04235.pdf
code adapted from: https://github.com/DeadAt0m/adafactor-pytorch
As of now, no learning rate is required (set it to zero to avoid confusion in stats).
Convergence is way faster than Adam, I am checking if results are as good.
Takes less memory than Adam, we can use much bigger batches.
TODO:
rsqrt warmup (not sure this gives much better results)

Introducing Adafactor

---

onmt/modules/average_attn.py

Fix comments in AAN module

---

CHANGELOG.md
onmt/__init__.py
onmt/trainer.py
setup.py

fix torch.no_grad for validation + Bump version

---

onmt/models/model_saver.py
onmt/opts.py
onmt/train_single.py
onmt/trainer.py
onmt/utils/__init__.py
onmt/utils/optimizers.py

The main change is to serialize the optimizer state and not the instance itself. Saving the instance restricted changes applied to the class and the use of optimizer wrappers. This change is backward compatible with existing checkpoints.
The learning rate management is also updated: the learning rate value is always computed dynamically based on the initial learning rate and the current training step. The learning rate decay schedules are expected to be passed as callable taking a step and returning a scaling factor.

Refactor Optimizer class

---

onmt/inputters/audio_dataset.py
onmt/inputters/dataset_base.py
onmt/inputters/image_dataset.py
onmt/inputters/inputter.py
onmt/inputters/text_dataset.py
onmt/opts.py
onmt/train_single.py
onmt/trainer.py
onmt/translate/translation.py
onmt/translate/translator.py

This pull request removes the `data_type` class attribute from various `Dataset` classes, which previously were unnecessary in the sense that the data type can be known from the type of the dataset, but necessary in the sense that the training and translation code (including all three methods that translate a batch) made reference to them.

Dataset data type attr

---

onmt/inputters/audio_dataset.py
onmt/inputters/image_dataset.py
onmt/inputters/inputter.py
onmt/inputters/text_dataset.py

Reverts OpenNMT/OpenNMT-py#1196
@flauted it breaks backward compatibility for models that have feature_tokenize in inputter.inpputer.py

Revert " Move batching and field logic from inputter to dsets"

---

onmt/utils/statistics.py

Fixes #1129 by making the import of distribution utilities conditional upon CUDA toolkit availability.

Make imports conditional on CUDA toolkit existence.

---

onmt/tests/pull_request_chk.sh

Downloading data for ``pull_request_chk.sh`` is somewhat time consuming. This PR fixes that by (1) providing an option to not delete the downloaded and untared data, and (2) providing an option to only download if the data isn't already there. Also cleans up (minus the log file) on error exit.

Add envs to make pull request script better for repeat runs.

---

onmt/inputters/inputter.py
onmt/opts.py
preprocess.py

This is required to execute some code paths (e.g. Tensor Cores on NVIDIA cards).

Option to pad the vocabulary size to a multiple

---

onmt/decoders/transformer.py

self_attn is an attribute of `TransformerDecoderLayer`, not `TransformerDecoder`.

Fix incorrect self attention type checking

---

onmt/inputters/audio_dataset.py
onmt/inputters/dataset_base.py
onmt/inputters/image_dataset.py
onmt/inputters/text_dataset.py
onmt/utils/misc.py

Read dataset files in bytes, decode to utf-8 later

---

CHANGELOG.md
onmt/__init__.py
setup.py

Bump minor version

---

onmt/decoders/transformer.py

This value is cheap to generate, there is no need to keep 150MB of buffers around.

Do not cache Transformer decoder mask

---

onmt/inputters/audio_dataset.py
onmt/tests/test_audio_dataset.py

This also fixes a bug when using batch first with AudioSeqField.

Add tests and docs for AudioSeqField.

---

onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/modules/multi_headed_attn.py
onmt/opts.py
onmt/utils/misc.py

#1198 
(This is heavily inspired by the tensor2tensor implementation.)
I did not test extensively but this seems to run properly.
Also, it does not seem to hinder performance much. I notice less than 5% slowdown on a single GTX 1080.
This is activated by setting the `-max_relative_positions` option. The default value in t2t is 20.

Relative Position Representations

---

onmt/inputters/audio_dataset.py
onmt/inputters/datareader_base.py
onmt/inputters/dataset_base.py
onmt/inputters/image_dataset.py
onmt/inputters/inputter.py
onmt/inputters/text_dataset.py

Better documentation for data pipeline

---

.travis.yml
onmt/decoders/decoder.py
onmt/decoders/transformer.py
onmt/models/model.py
onmt/modules/global_attention.py
onmt/opts.py
onmt/translate/translator.py

Trying to:
- maintain the inline documentation according to recent changes.
btw: @flauted @bpopeters youmay have to do so for the Dataset recent changes, that would  be great.
- make the change "fast translate" becoming default and legacy becoming "deprecated" still in the code for now, but to be removed.
@sebastianGehrmann @guillaumekln are you guys ok ?
we need to move on I think.

doc clean-ups, remove old beam

---

CHANGELOG.md
onmt/__init__.py
onmt/translate/translator.py
setup.py

Bump version 0.8.0

---

onmt/translate/translator.py

Came up on #1292 that this might be useful. Old regular Translator init -> from_opt, new regular init.

Add from_opt constructor to Translator

---

.travis.yml
onmt/decoders/ensemble.py
onmt/tests/pull_request_chk.sh

Fixes #1300 .
Tests it in Travis and the pull request check script.

Fix and test ensemble decoding

---

onmt/decoders/ensemble.py

#1299 broke ensemble decoding. This fixes it.

Fix ensembling again.

---

.travis.yml

disable deploy doctr

---

onmt/decoders/cnn_decoder.py
onmt/decoders/decoder.py
onmt/modules/global_attention.py
onmt/opts.py
onmt/tests/test_models.py
onmt/translate/decode_strategy.py
onmt/translate/translator.py
onmt/utils/parse.py

This closes #1063 (thanks to the author of that PR- this is based on that) and closes #574 .
This makes it possible to disable global attention. Copy attention can still be used. This also decouples the global attention type and the copy attention type.
----
Here's some tests/demos:
**Backwards compatibility/regression**
```
python translate.py -model /home/dylan/Downloads/gigaword_nocopy_acc_51.33_ppl_12.74_e20.pt -src /home/dylan/Downloads/sumdata/Giga/input.txt -tgt /home/dylan/Downloads/sumdata/Giga/task1_ref0.txt -min_length 35 -verbose -stepwise_penalty -coverage_penalty summary -beta 0.2 -length_penalty none -gpu 0
```
Master:
```
PRED AVG SCORE: -1.8371, PRED PPL: 6.2781
GOLD AVG SCORE: -10.7468, GOLD PPL: 46480.8489
```
This:
```
PRED AVG SCORE: -1.8371, PRED PPL: 6.2781
GOLD AVG …
```

Disable attention

---

onmt/inputters/audio_dataset.py

On Speech to text task.
In AudioSeqField class
You forgot to map "arr" to the device.

Bug fix of AudioSeqField

---

onmt/translate/translation_server.py

---
* it fixes https://github.com/OpenNMT/OpenNMT-py/issues/1339

Fix UTF-8 encoding error in translation server (python2 only)

---

onmt/decoders/decoder.py

Fixes #1337 .
I don't think any of the pretrained models use coverage, so I'm not sure how to test for regression.

Map state on coverage if coverage is there

---

onmt/decoders/ensemble.py

Part of #1334 (there's another issue there that this doesn't address). Haven't had a chance to test it beyond the pull request check.

Have EnsembleDecoder set attentional property.

---

onmt/trainer.py

This PR aims at not breaking a training when the GPU Ram is almost at the limit and when a few batches may just make it go OOM. It will just discard the batch.
If you see too many "discard" messages then you'd better reduce the batch size.

Better handle Cuda OOM with overflow batches

---

docs/source/Library.md

To follow up on https://github.com/OpenNMT/OpenNMT-py/issues/1390#issuecomment-482639810

fix Runtime error in Library tutorial

---

docs/source/onmt.modules.rst
onmt/opts.py

Hello.
I fixed spelling mistakes. Please check this PR.
Thank you.

fix spelling mistakes

---

.travis.yml

There is a performance gain in upgrading to pyTorch 1.1

Upgrade Travis to pyTorch 1.1

---

onmt/models/model_saver.py

When validating over some examples which contain some tokens that were not seen during vocab building at preprocessing, those tokens are added to the end of the vocab, with id "0".
This leads to some upsetting behaviours where we can't ensemble some models that are supposed to be trained on the same vocabulary. (triggering this [assert](https://github.com/OpenNMT/OpenNMT-py/blob/1b3cc33601a7d22c340044ddd7fc29f96267fae8/onmt/decoders/ensemble.py#L146))
So, we propose to trim the vocab that is saved, removing every token with id "0" which is not the `unk_token`.

[fix] Trim vocab when saving checkpoint

---

train.py

[fix] Make queue.put() blocking again

---

CHANGELOG.md
onmt/__init__.py
onmt/opts.py
preprocess.py
setup.py
train.py

Bump version 0.9.1.
Add option to overwrite shards when preprocessing.
Handle single `opt.data_ids`.

Bump 0.9.1

---

CONTRIBUTING.md

Fixes #1470 which was oddly immediately closed despite being confirmed

fix incorrent script path in CONTRIBUTING.md (#1470)

---

server.py

this exposes a simple `GET` method for seeing if the server is alive, useful for orchestration frameworks as well as individuals wanting to see if the server is running smoothly.

add health endpoint to server.py

---

onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/modules/average_attn.py
onmt/modules/multi_headed_attn.py
onmt/opts.py
onmt/tests/pull_request_chk.sh

Benchmark, with Base transformer, batch_size 384, 3000 sentences (not sorted by length)
Regular transformer
PRED AVG SCORE: -0.0036, PRED PPL: 1.0036
Total translation time (s): 20.975219
Average translation time (s): 0.006992
Tokens per second: 3698.030475
AAN transformer
PRED AVG SCORE: -0.0001, PRED PPL: 1.0001
Total translation time (s): 13.076423
Average translation time (s): 0.004359
Tokens per second: 5842.117452

Optimize AAN transformer and small fixes

---

docs/source/index.rst
docs/source/vid2text.rst
onmt/decoders/transformer.py
onmt/encoders/encoder.py
onmt/encoders/transformer.py
onmt/inputters/__init__.py
onmt/inputters/inputter.py
onmt/inputters/vec_dataset.py
onmt/model_builder.py
onmt/modules/__init__.py
onmt/modules/embeddings.py
onmt/opts.py
onmt/utils/parse.py
tools/vid_feature_extractor.py

This PR introduces sequence of feature vectors -> text translation. It includes a tutorial for video captioning in the style of ["Describing Videos by Exploiting Temporal Structure"](https://arxiv.org/pdf/1502.08029.pdf).
WIP because I want to include one or two other approaches/architectures so that the abstraction is at the right level from the start.

Video captioning

---

onmt/translate/translation_server.py

Add preprocess_opt for preprocess the input sequence, helps for chinese related translation task.
TO-DO: do the same for postprocessing.

Add preprocess_opt in rest server (ZH)

---

onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/models/model.py
onmt/opts.py
onmt/tests/test_models.py
onmt/utils/parse.py

So far attention_dropout was the same value as dropout
trying to have different values to stick to the paper.

add attention_dropout separate from dropout

---

onmt/opts.py
onmt/translate/translator.py
translate.py

This PR is just to introduce token batching for translation.
The idea is to have a more homogeneous GPU usage when translating big files (e.g. backtranslation).

Tokens batch for translation

---

onmt/utils/optimizers.py
requirements.opt.txt
requirements.txt

update FP16 test since Apex AMP changed its class names.

fix Apex API

---

requirements.txt

Add missing requirement for video captioning (#1562).

add pretrainedmodels to requirements.opt.txt

---

docs/requirements.txt

https://pypi.org/project/sphinx-markdown-tables/

Make sphinx support markdown tables

---

onmt/__init__.py
setup.py

Preview: https://test.pypi.org/project/OpenNMT-py/1.0.0rc20/

Add project metadata

---

.travis.yml
onmt/bin/server.py
onmt/inputters/image_dataset.py
onmt/utils/logging.py
requirements.opt.txt
setup.py

+ Use waitress by default instead of Flask experimental server;
+ update requirements to torch 1.3.1;
+ force pillow version to <7 (https://github.com/pytorch/vision/issues/1712);

Use waitress by default for REST server, add some debugging logs

---

onmt/utils/optimizers.py

Update path for apex FP16_Optimizer

---

onmt/bin/release_model.py

This requires CTranslate2 >= 1.6.

Enable CTranslate2 conversion of Transformers with relative position

---

README.md

According to https://github.com/OpenNMT/OpenNMT-py/blob/master/setup.py#L25

[docs] Need torch 1.4 in REAMMD.md

---

onmt/translate/translation_server.py

#1747 was not the right fix.
And #1745 was breaking support of n_best.
This PR should set things straight.

[fix] Handling of empty segments in REST server + n_best

---

onmt/translate/translation_server.py
onmt/utils/logging.py

Rotate only the server logs

---

onmt/bin/preprocess.py
onmt/bin/train.py
onmt/inputters/__init__.py
onmt/inputters/dataset_base.py
onmt/inputters/inputter.py
onmt/modules/__init__.py
onmt/modules/source_noise.py
onmt/opts.py
onmt/trainer.py
onmt/translate/translator.py

Code is based on fairseq's BART: https://github.com/pytorch/fairseq/blob/master/fairseq/data/denoising_dataset.py

Experimental: source noise similar to BART

---

onmt/bin/preprocess.py
onmt/bin/train.py
onmt/inputters/inputter.py
onmt/train_single.py

[fix] Patch (old) fields when missing corpus_id

---

.travis.yml
onmt/bin/preprocess.py

In the current setup, features count was added for each dataset instead of just checking we have the same feature count for each dataset.

[fix] Fix count of features when multiple datasets

---

onmt/decoders/transformer.py

some comments in transformer.py are misleading.

fix wrong descriptions in transformer.py

---

onmt/bin/translate.py

Pass logger when building translator

---

onmt/translate/translation_server.py

This PR adds support to the `target_prefix` feature for ct2 models in the REST server.

support target_prefix for ct2 model in REST server

---

onmt/translate/decode_strategy.py

In this PR, we improve `target_prefix` by penalizing non chosen token in the vocab rather than reward the candidate.
This helps in:
* makes it more stable and possible to be used with `length_penality` to avoid potential decoding failure;
* score impact from prefix part can be therefore ignored compare to the previous version, making prediction score consistent.

Better target_prefix by penalize non chosen vocab

---

onmt/bin/train.py
onmt/inputters/inputter.py
onmt/train_single.py

Pasted from @Zenglinxiao:
Recently when running OpenNMT-py with PyTorch 1.6, the following error will be encountered:
[W CudaIPCTypes.cpp:90] Producer process tried to deallocate over 1000 memory blocks referred by consumer processes. Deallocation might be significantly slowed down. We assume it will never going to be the case, but if it is, please file but to https://github.com/pytorch/pytorch
This is due to the sharing strategy of CUDA tensor.
To fix it, we can either:
- keep sending CUDA tensor in producer but release them ASAP in the consumer;
- or just send CPU tensor and convert to CUDA tensor in consumers.
Unfortunately, I haven't achieved to fix it with the first approach.
This PR solves it in the second approach, and it's also used in my dynamic training mechanism.
By sending CPU …

Fix deallocate warning

---

onmt/inputters/image_dataset.py

Auto convert image to 3 channel (RGB) when using channel_size 3

---

onmt/transforms/bart.py

[fix] Type mismatch in BART transform

---

onmt/transforms/tokenize.py
requirements.opt.txt
setup.py

Followed by the suggestion in #1912.

update required version for pyonmttok/sentencepiece

---

CHANGELOG.md
onmt/__init__.py
setup.py

Some fixes were made since rc1. This will also allow to test auto deploy with GitHub Actions.

Bump 2.0.0rc2

---

docs/source/examples/Library.ipynb

[docs] Fix build_vocab in Library example

---

build_vocab.py
data/morph_data.yaml
onmt/model_builder.py
onmt/tests/rebuild_test_models.sh

This PR also adds the `build_vocab.py` entry point script at the root of the repo.
And fixes and assert message that mentions preprocessing.

Update rebuild test models script for 2.0 paradigm

---

onmt/bin/build_vocab.py

fixes #1948 
Apologies, I didn't follow the guideline to run onmt/tests/pull_request_chk.sh because I'm on windows.  One assumes this won't break other parts of the engine, but who knows.

fixes https://github.com/OpenNMT/OpenNMT-py/issues/1948

---

setup.py

Upgrade torchtext to 0.5.0

---

onmt/modules/copy_generator.py

`(batch x tlen, input_size)`->`(batch x tlen, slen)`

Fix `attn` shape annotation in `forward`

---

onmt/inputters/text_dataset.py
onmt/modules/embeddings.py
onmt/tests/test_translation_server.py
setup.py

The project only supports Python 3.5 and above.

Remove six dependency

---

onmt/__init__.py
onmt/bin/translate.py
onmt/opts.py
onmt/tests/test_data_prepare.py
onmt/translate/penalties.py
onmt/translate/translation.py
onmt/translate/translation_server.py
onmt/translate/translator.py
onmt/utils/distributed.py
onmt/utils/logging.py
onmt/utils/loss.py
onmt/utils/report_manager.py
onmt/utils/statistics.py
setup.py

This project no longer supports Python 2.

Remove no longer needed future dependency

---

docs/source/examples/GGNN.md
examples/ggnn.yaml
onmt/encoders/ggnn_encoder.py
onmt/opts.py

Multiple users have requested this, and I believe it will be valuable for my own further research. Along with this feature addition, I have cleaned up the documentation and improved the end-to-end example.

Support embedding layer for larger vocabularies with GGNN

---

onmt/opts.py
onmt/translate/translator.py

This commit intends to make a better organization of translation options since the current one seems a little bit ambiguous.

clarify translation options

---

onmt/inputters/inputter.py
onmt/transforms/transform.py

This is to solve an issue I've been having trying to train models. I haven't been able to reproduce on my dev machine but I think this should fix the issue.
- https://forum.opennmt.net/t/opennmt-py-error-when-training-with-large-amount-of-data/4310

Handle invalid lines in vocab file gracefully

---

docs/requirements.txt

https://github.com/sphinx-doc/sphinx/issues/9001

Force docutils <0.17 which breaks docs generation

---

README.md

Unexpected and uncomfortable read while evaluating the project
(Off-topic: It looks like it's exactly what I'm looking for, thanks for your hard work!)

README: Update "Validation files" example

---

.github/workflows/push.yml
onmt/model_builder.py
onmt/tests/pull_request_chk.sh

Encoder fields do not exist for language models. A check must be performed before deleting or updating those fields.

Fix update_vocab for LM

---

onmt/inputters/text_dataset.py

This PR fix a bug which leads to incorrect 'indices' from reader

fix a bug which results in wrong indices in reader

---

docs/source/FAQ.md

Source: https://forum.opennmt.net/t/simple-opennmt-py-rest-server/1392

add server documentation

---

onmt/inputters/dataset_base.py

@francoishernandez 
Solution to this issue #2110

Fixed bug when no features set in database_base

---

requirements.opt.txt

https://github.blog/2021-09-01-improving-git-protocol-security-github/

[CI] Switch git:// to https:// for apex requirement

---

.github/workflows/push.yml
onmt/decoders/cnn_decoder.py
onmt/decoders/decoder.py
onmt/encoders/cnn_encoder.py
onmt/encoders/rnn_encoder.py
onmt/models/model.py
onmt/trainer.py

Must have not been used by anyone for a long time but when setting multiple values of dropout / attention_dropout
it failed because missing second parameter in method.
fix #2193

fix bug drop_out scheduling

---

onmt/tests/test_beam_search.py
onmt/translate/beam_search.py

@funboarder13920 please check the very last test_beam_search in test_beam_lm_update_memory_length_when_finished(self), because I made a change without knowing exactly why this PR requires this change.
Thanks.

Change beam exit condition

---

README.md
setup.py

set torch version to >1.9.0

---

onmt/inputters/dynamic_iterator.py

When building tokens batches on the fly based on sorted buckets, make sure there is no duplicate based on source tokens.

dedup batches on the fly

---

onmt/opts.py
onmt/trainer.py
onmt/utils/scoring_utils.py

This PR is a patch for unproperly fixed dynamic scoring at evaluation time in v.3. (#2253)
Also adds missing `""` entry in apex_opt_level choices. (#2220)

Fix validation scoring

---

.github/workflows/push.yml
README.md
config/config-transformer-base-1GPU.yml
config/config-transformer-base-4GPU.yml
docs/source/FAQ.md
docs/source/examples/Translation.md
docs/source/main.md
examples/onmt.train.fp16.transformer.yaml
examples/wmt14_en_de.yaml
onmt/model_builder.py
onmt/tests/pull_request_chk.sh
onmt/tests/rebuild_test_models.sh
onmt/tests/test_models.sh
onmt/trainer.py
onmt/transforms/transform.py
onmt/translate/translator.py
onmt/utils/loss.py
tools/LM_scoring.py

This brings 10-25% speed improvement at training depending on configs.

Use native CrossEntropyLoss including label_smoothing + more optimisations

---

onmt/trainer.py
onmt/utils/loss.py

In v3.0 (vs v2.3) we introduced an approximated normalization when accum > 1 or nb gpu > 1.
This PR reverts this behavior and normalizes the loss on the exact number of tokens of the global true batch.

revert approx normalization to accurate per item

---

onmt/utils/loss.py

There was a mistake in the LM prior implementation.
(the PR for v2 was fine but for v3 there was a mistake in the passing the target to the LM, BOS was omitted)
this PR fixes it.

fix bad mistake in lm prior

---

.github/workflows/push.yml
onmt/inputters/dynamic_iterator.py
onmt/tests/pull_request_chk.sh
tools/LM_scoring.py

release batch_size=1 forcing in dynamic iterator.
warning is still in the translate_batch()
accordingly re-instate batch LM scoring for speed.

fix LM scoring

---

onmt/decoders/transformer.py
onmt/utils/scoring_utils.py

reset cache during training

---

docs/source/FAQ.md
onmt/model_builder.py
onmt/train_single.py
onmt/transforms/misc.py
onmt/transforms/normalize.py
onmt/utils/optimizers.py

also fix a bug in the prefix apply_reverse

add normalize transform

---

onmt/utils/alignment.py

There seems to be typo concerning alignment map for target sentence

target map fix for alignment

---

onmt/bin/build_vocab.py

@vince62s This is the PR to fix indexing issues for the vocabulary building script.

Fixed build vocab indexing issue

---

onmt/translate/translation_server.py

Hi @vince62s ,
This PR fixes issue https://github.com/OpenNMT/OpenNMT-py/issues/2325

Fixed server device index issue

---

onmt/inputters/inputter.py
onmt/inputters/text_utils.py
onmt/opts.py
onmt/translate/translator.py

There was a missing part to be able to train NLLB-200 (finetuning).
Now it works.

fix NLLB-like decoder_start_token at training

---

docs/source/FAQ.md
onmt/translate/translation_server.py

added alignment support to CTranslate2Translator object, using attention reported by ctranslate2.

added report_align support for ctranslate2

---

onmt/model_builder.py

fix a bug introduced with the LoRa PR which made all non LoRa models non-trainable ....

fix bug from LoRa PR

---

onmt/transforms/inlinetags.py

- Fix space issue when adding a stand alone tag
- Fix corpus ratio logic

Space and ratio fixes to inlinetags transform

---

onmt/bin/build_vocab.py
onmt/opts.py
onmt/transforms/clean.py
onmt/transforms/fuzzymatch.py
onmt/transforms/inlinetags.py
onmt/transforms/misc.py
onmt/transforms/normalize.py
onmt/transforms/tokenize.py
onmt/utils/parse.py

Adding the subword learning option to build_vocab.
Just took the scenario where we build the subword model on both the source and target. If someone is interested in separate bpe for src/tgt, PR welcome.
I also changed the transform logs to "debug" to make less noise during training.
init_logger is by default "info". again this cold be an option, PR welcome.

optional subword learner in build_vocab

---

onmt/decoders/transformer.py

fix avg attn cache

---

onmt/modules/lora.py

When we use a quantized layer along with a LoRa adapter we cannot merge/unmerge weights during training / eval [ we would need extra operations to unquantize merge and requantize] hence Validation with such a config is not a real validation it just take the pretrained model.

prevent from merge/unmerge LoRA weights with quantized weights

---

.gitignore
onmt/bin/train.py
onmt/decoders/__init__.py
onmt/encoders/__init__.py
onmt/opts.py

Allow to use plugin encoder and decoder

---

onmt/inputters/dynamic_iterator.py
onmt/utils/rnn_factory.py

Debug minor fix for `onmt/inputters/dynamic_iterator.py` and `onmt/utils/rnn_factory.py`

Debug minor fix

---

onmt/inference_engine.py

missing file for the tensor parallelism ...

missing file

---

onmt/model_builder.py
onmt/models/model.py
onmt/models/model_saver.py
onmt/utils/distributed.py
setup.py

fix data_parallel loading

---

onmt/translate/translator.py

fixes https://github.com/OpenNMT/OpenNMT-py/issues/2471

Fix for coverage penalty error during translation

---

setup.py

Fixes https://github.com/OpenNMT/OpenNMT-py/issues/2475

Fix torch requirement

---

README.md

fixes https://github.com/OpenNMT/OpenNMT-py/issues/2475

Update torch version in readme

---

onmt/models/model.py
onmt/tests/test_embeddings.py

refactor to align pytroch ckpt and safetensors ckpt.
fix state_dict keys when using copy_generator

Model loading

---

onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/modules/multi_headed_attn.py
onmt/opts.py

Support both rotary interleave and no interleave to support natively HF LLM models.

Add rotary_interleave=false (Hugging face models)

---

onmt/modules/multi_headed_attn.py

fix rope device for long sequence

---

onmt/opts.py
onmt/tests/test_inference_engines.py

Not the nicest thing to do since this option is part of model_opt for training but easiest way to force it at inference.

Defaultflash

---

onmt/modules/multi_headed_attn.py

fix generation with large sequences when flash2 is False

fix generation with large sequences when flash2 is False
