onmt/modules/GlobalAttention.py
translate.py

It is better to use `float('-inf')` instead of `math.inf` since `math.inf` is only supported in python 3+.
Python 2.7 throws the error `AttributeError: 'module' object has no attribute 'inf'` at `attn.data.masked_fill_(self.mask, -math.inf)` line. 
Also in `translate.py` file `predBatch[b][0]` should be `predBatch[b][n]` instead to print the nth best sequence.

use `float('-inf')` instead of `math.inf` (py3+ support only)

---

translate.py

Hi, 
When I tried running `translate.py` with a specified `-max_sent_length` parameter,
I found that it fails because the argument type is not specified (and considered as str).
E.g., 
```
$ python translate.py ...(other parameters)... -max_sent_length 30 ...
Traceback (most recent call last):
File "translate.py", line 135, in <module>
main()
File "translate.py", line 89, in main
predBatch, predScore, goldScore = translator.translate(srcBatch, tgtBatch)
File "/Users/sotetsuk/github/OpenNMT-py/onmt/Translator.py", line 197, in translate
pred, predScore, attn, goldScore = self.translateBatch(src, tgt)
File "/Users/sotetsuk/github/OpenNMT-py/onmt/Translator.py", line 117, in translateBatch
for i in range(self.opt.max_sent_length):
TypeError: 'str' object cannot be interpreted as an integer …
```

Fix a bug of missing arg type

---

preprocess.py

when there's an empty line on either side of the parallel corpus, preprocess.py ignores any line from thereon with only a warning message. this pr makes preprocess.py effectively ignore any line in which either source or target side is empty.

ignore empty lines in preprocess.py

---

onmt/Dataset.py
onmt/Models.py
train.py

`DataParallel` splits input `Variable`s alongside the second dimension but the lengths metadata was a plain Python list, thus throwing an error. This PR temporarily make the lengths array a 2D `Variable`, like the actual input.
Fixes #34 and #28.

Fix DataParallel with variable lengths

---

train.py

it's a trivial thing but the optimiser function appears to be documented around using perplexity instead of loss and the input in this line is loss and not perplexity

optim function expects perplexity

---

onmt/Models.py

latest PyTorch (commit 32e6665) `Variable().t()` function does not support 3-D tensor transposition, using `.transpose()` instead.

change `t()` to `transpose(0, 1)` for latest pytorch support

---

README.md
onmt/Models.py
onmt/modules/Gate.py
train.py

I have added the three versions "source", "target" and "both" context gate as explained in the referenced paper.
I have extended the Decoder class for using the context gate, and it can integrated also in future different decoders very easily.
Reference paper:
Tu, Zhaopeng, et al. "Context gates for neural machine translation." arXiv preprint arXiv:1608.06043 (2016).

Context Gates

---

onmt/modules/GlobalAttention.py
translate.py

The BottleLinear transformation applied in MLP attention adds an extra singleton dimension that should be removed. The previous solution was to squeeze the resulting tensor. However, this squeezing will also remove the source length dimension if the the source length was 1; therefore, I changed squeeze to only remove the dimension 2, which I believe is the intended behavior.
I also added a fix for the string-decoding thing in translate.py that broke translation for python3 users. This is not a permanent fix as I am not aware of all the encoding issues facing python2 folks; I just wanted it to stop crashing when I was using it in python3.

Fix a bug in attention dimension with MLP attention

---

onmt/Models.py
onmt/modules/GlobalAttention.py
test/test_models.py
train.py
translate.py

The option for dotprod attention in GlobalAttention in fact matched Luong et al.'s specification of general attention. I fixed the naming of these options and added an attention option that corresponds to the dot product method of scoring in the Luong paper. 
I refactored the attention-scoring a little bit so now the batch x source length attention score tensor can be created by a helper score function. If the GlobalAttention class were only concerned with the mechanisms from Luong et al.'s paper, it would be possible to handle all of their attention types simply by subclassing the thing and defining a new score function and layers as necessary. However, the process for MLP has a few different steps later on in forward().

Add distinct options for general and dotprod attention

---

train.py

Just found that, if `-save_model`'s parent directory is missing we get an error **after** training the first epoch (on first checkpoint saving attempt) which does not make sense and waste time.

Creating model directory if missing

---

onmt/Models.py
test/test_models.py
train.py

This pull request adds support for concatenation of word and feature embeddings. Namely, if you have an x-dimension word embedding and a y-dimensional feature embedding, then these will be concatenated into an (x+y)-dimensional embedding for the encoder. This is the default setting for using features in Lua.
I believe the previous behavior of the embeddings class corresponds to the sum behavior, so I preserved it with the sum option.
The goal is for the interface to be the same is in Lua OpenNMT. Consequently, the command line interface has been changed slightly to match Lua.
`-feat_merge` accepts concat and sum; the default is concat
`-feat_vec_exponent` defaults to 0.7; it is used to compute size of feature embeddings when using concat
`-feature_vec_size` is now `-feat_vec_size` and its …

Add concatenative feature embeddings

---

preprocess.py

Hi,
I am requesting this PR for allowing values 0 for attributes src_vocab_size, tgt_vocab_size. This would allow no pruning of the vocabulary.
Currently, we can either use default 50000 or manually find out the vocab size to disallow pruning.

Allowing to provide value 0 for no pruning of src and target vocabulary

---

onmt/Models.py
train.py

train.py currently does not work if the string passed to -save_model does not contain a directory because of the changes made in pull request #143 . I changed so that training is possible if -save_model contains a string with no directory-separating characters. For example, with the command 
`python train.py -data data/demo.train.pt -save_model demo-model`
the model .pt file will be located inside the OpenNMT-py directory. I believe this was the behavior before #143 .
In the event that -save_model contains multiple directories, i.e. `foo/bar/baz/model_name`, intermediate directories will also be made to make sure that the path exists.

Fix issue #158

---

onmt/Models.py
test/test_models.py
train.py

In my previous PR, I referred to the feature merging strategy that used MLP as "sum". As Guillaume Klein pointed out, this is not correct. Therefore, I have revised the code to include a legitimate sum option. I added an extra feature merging option in train.py, `-feat_merge mlp`, for the MLP case. There are still some bits that might need to change regarding the sizes of features. Current behavior is that if merge is` concat`, the `feat_vec_exponent` is used for determining sizes. If the merge is `mlp`, `feat_vec_size` is used. And if the merge is `sum`, `word_vec_size` is used.

Add sum feature embeddings

---

onmt/Models.py

The previous way of doing coverage attention breaks Models.py because boolean tests cannot be done on tensors. This PR provides a minimal fix.

Fix coverage attention

---

onmt/Models.py
onmt/modules/GlobalAttention.py

RNN decoder processes one token at a time during training. 
When `-input_feed` is disabled, RNN forward and attentions can be computed in parallel at sequence level instead of token level.
This gives a  > 2x speed-up, tested on a GTX 1080 card:
**before:**  ~4,000 tokens / sec
**after:**  ~10,000 tokens / sec

speed improvement when input_feed = 0

---

onmt/Translator.py

Thanks for fixing #188 . When I run translate.py with --tgt and --gpu 1 I get the following stack trace, which should be fixed by the pull request.
```
File "translate.py", line 151, in <module>
main()
File "translate.py", line 94, in main
= translator.translate(batch, data)
File "/home/marcotcr/OpenNMT-py/onmt/Translator.py", line 188, in translate
pred, predScore, attn, goldScore = self.translateBatch(batch, data)
File "/home/marcotcr/OpenNMT-py/onmt/Translator.py", line 163, in translateBatch
allGold = self._runTarget(batch, dataset)
File "/home/marcotcr/OpenNMT-py/onmt/Translator.py", line 83, in _runTarget
goldScores += scores
File "/home/marcotcr/.local/lib/python2.7/site-packages/torch/tensor.py", line 297, in __iadd__
return self.add_(other)
TypeError: add_ received an invalid …
```

minor fix in translator to make it work with tgt and gpu

---

CONTRIBUTORS.md
onmt/IO.py
onmt/Models.py
onmt/Translator.py
onmt/modules/Transformer.py
test/test_models.py
tools/extract_embeddings.py
tools/pull_request_chk.sh
train.py

This is the first patch series, addressing Issue https://github.com/OpenNMT/OpenNMT-py/issues/196.
This patch series refactors the `Encoder` class.
To do this, I chose a bottom-up way, that is refactoring the class used in `Encoder` class first, which are
`Embeddings` class and `TransformerEncoder` class, then refactor the `Encoder` class itself.
For the `Embeddings` class, since it is also used by `Decoder` class, which I will refactor in later series,
I collect its needed options into a dictionary. So the `Encoder` class constructor would not be too cluttered.
To ease review, I split the patches into 4 parts incrementally:
patch 76fcdda2c5a2:  just a arg tidy-up.
patch 576d9cb560ac:  prep patch, refactored the `Embeddings` class
patch 49143d84ae20:  prep patch, refactored the …

Refactor Encoder class constructor to take needed options explicitly. 

---

onmt/IO.py

There is a bug right now that prevents preprocessing with the `dynamic_dict` option. This is due to stoi in torchtext.vocab.Vocab using a defaultdict with a lambda function. These functions are not pickleable without using dill. 
Since we got rid of dill, we need a change to torchtext itself. For now, I built a workaround but we should ping the guys to change the stoi defaultdict to a named function or to return a normal dict in `__getstate__`

Fix bug that dynamic_dict cannot be used with pickle

---

onmt/Models.py
onmt/modules/ImageEncoder.py

This pull request has only one patch:
e7c1acb:  ImageEncoder: Modify its constuctor for accepting options explicitly
It would have been part of the `Encoder` refactorization series, but since it is quite independent from other parts, thus it warrants a standalone patch.

ImageEncoder: Modify its constuctor for accepting options explicitly

---

onmt/IO.py
onmt/Loss.py
onmt/Translator.py
preprocess.py

The goal of this pull request is to simplify the process by which source and target files are read in and converted into ONMTDataset objects. The contributions can be divided into three parts:
1) I shortened `extractFeatures` so that the reader of code no longer needs to keep track of indexing logic, but merely a sequence of comprehensions with descriptive names. This also allows the assertion requiring all words to have the same number of features to be expressed in a clearer way. The `zip(*split_tokens)` trick is not always completely intuitive to the reader, but it is well-documented on the internet as a way to unzip a zipped sequence.
2) I rewrote the `ONMTDataset` constructor. Its previous iteration had two large loops, one for the source file and the other for the target file. I …

Refactor IO.ONMTDataset

---

onmt/IO.py
onmt/Models.py
onmt/Translator.py
test/test_models.py
train.py

This pull request makes a few small changes to IO.py, Models.py, Translator.py, and train.py. The goal of the changes is to make it to get rid of some of the artificial barriers that are currently standing in the way of implementing target features.
I have eliminated two of these obstacles:
1. Previously, `Decoder.forward()` expected an input whose dimensions were length x batch_size. A third dimension, analogous to the nfeat dimension used in the encoder, is added. Tensor logic is changed as necessary in the decoder to make use of these new dimensions.
2. Code in other files is changed as necessary so that the target variables passed to the decoder will be the correct size. This required abstracting out `make_features` in IO.py: now it accepts a batch object and a side (src or tgt) and …

Give decoder input an nfeat dimension

---

onmt/Models.py
onmt/modules/Conv2Conv.py
onmt/modules/Embeddings.py

This pull request addresses the bug discussed in #261. Incorrect embedding dimensions were getting passed all over the place. Some of these errors are the results of recent pull requests, while the ones with `mlp` have been around for longer. Getting training with features up and running again allows us to train test models that use features, which should make it more difficult for errors like this to arise again in the future.
Besides fixing the mlp issue, the state of Embeddings.py is now essentially the same as it was a week ago, the difference being that some of the argument names have changed. I had tried to keep them close to the relevant command line names (i.e. `word_vec_size` and `feat_vec_size` in the old version versus `embedding_dim` and  `feat_embedding_size` currently), but …

Fix embedding bug

---

onmt/Beam.py
onmt/Loss.py
onmt/ModelConstructor.py
onmt/Translator.py
onmt/Utils.py
train.py

This PR clarifies code in train.py and adjacent files. Specifically,
1. I clarified the process in train.py's `main()`. There used to be several separate if/elses regarding `opt.train_from`. Now there's just one.
2. I snake_cased variable and function names in train.py and Loss.py.
3. I removed the `Splitter` class. It had only one function and no interesting state, so I decided that its purpose would better be implemented with a generator function. I simplified the implementation of that function, replacing some indexing logic with a fair quantity of well-commenting zipping and unzipping. The function is renamed `shards`. I'm a little bit skeptical of backpropping the variables after the last yield of a generator function, but I don't know what would be a better way to do it.
4. Where …

Clean train.py and adjacent files

---

README.md
onmt/ModelConstructor.py
onmt/Models.py
onmt/modules/SRU.py
onmt/modules/__init__.py
opts.py
setup.py
test/test_models.py
train.py

This PR addresses Issue https://github.com/OpenNMT/OpenNMT-py/issues/251, trying to incorporate the author's implementation into our project. I am doing this by adding a new `-rnn_type`: **SRU** in `RNNEncoder` and `StdRNNDecoder`, not to create a new `SRUEncoder` and `SRUDecoder`. I think this makes much more sense - `SRU` is just a variant of `RNN`, the same as `LSTM` and `GRU`. Thanks to our modular structure, I am trying to keep this less intrusive to the code structure.  Hopefully sometime in the future when pytorch community supports this RNN variant, we could easily migrate to use it.
**Patch list**
This PR has 2 patches.
**1.** 97929d5 **RNNEncoder: Add a command-line option to disable pack_padded_sequence**
This is a preparing patch.  Since this SRU doesn't support …

Add support for "Training RNNs as fast as CNNs"

---

onmt/modules/Embeddings.py
opts.py

This pull request changes the behavior of the `-feat_vec_size` and `-feat_vec_exponent` command line options for building embeddings. Previously, `-feat_vec_exponent` was only used for `-feat_merge concat` and `feat_vec_size` was only used for `-feat_merge mlp`. This would lead to a lot of frustration if a person had pretrained feature embeddings of a known dimension that they wanted to concatenate, because they couldn't just specify that dimension with `-feat_vec_size`.
I changed this so that if `-feat_vec_size` is specified, it is used. `-feat_vec_exponent` is only used to determine the feature embedding size if `-feat_vec_size` is not specified.
I also changed around a couple of variable names in Embeddings.py to be clearer (`word_vec_size` is a better description of the variable's …

Change behavior for feature dimensions

---

onmt/Models.py
onmt/modules/SRU.py
test/test_models.py

This is a fix to the https://github.com/OpenNMT/OpenNMT-py/pull/260.
I forgot to check in this patch. 
SRU doesn't support InputFeed. So add a check in `make_decoder()` to use `StdRNNEncoder` instead.

SRU: fix the decoder when rnn_type SRU is used

---

translate.py

This PR makes a few changes to standardize the style and clarify what's going on in translate.py. These are just cosmetic changes, but they should ease future debugging of the script. I removed all indexing logic and accumulator variables and updated naming styles. I think it's possible to do even a little bit more, but incremental progress matters. Note that the `attn_debug` command line option is not actually implemented. This would be a useful future step.

Clean translate

---

train.py

It was calling .vocab on a string rather than a torchtext object

bug when trying to print out info about features

---

README.md

Fix wrong argument in tutorial document, when execute below command line, then
$ python train.py -data data/multi30k.atok.low.train.pt -save_model multi30k_model -gpuid 0
below error occured and I changed data argument to data/multi30k.atok.low , it works well.
Loading data from 'data/multi30k.atok.low.train.pt'
Traceback (most recent call last):
File "train.py", line 318, in <module>
main()
File "train.py", line 231, in main
train = torch.load(opt.data + '.train.pt', pickle_module=dill)
File "/opt/conda/envs/pytorch-py35/lib/python3.5/site-packages/torch/serialization.py", line 229, in load
f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/multi30k.atok.low.train.pt.train.pt'

fix wrong argument in tutorial document

---

onmt/ModelConstructor.py
opts.py

This is a small addition to model_constructor to enable shared embeddings between encoder and decoder. 
I tested by running a model with and without the option (wvec size 128, vocab size 50k) - The total parameters decreased by 6.4 mio as expected.

Add option to share embedding

---

onmt/Trainer.py
onmt/modules/CopyGenerator.py

- add `**kwargs` in `onmt.modules.CopyGenerator.CopyGeneratorLossCompute.forward`
- set `copy_attn` parameter for `validation_loss` in `Trainer`
Fixing #313

Fixing copy_attn validation

---

onmt/IO.py
test/test_preprocess.py

When using the preprocessing option `share_vocab`, the called function `merge_vocab` had unintended behavior. 
Namely, instead of adding the token frequencies of the src and tgt vocabularies, it counted in how many dictionaries a word appeared in. Example behavior below:
```
va = torchtext.vocab.Vocab(Counter('abbccc'))
vb = torchtext.vocab.Vocab(Counter('eeabbcccf'))
print(merge_vocabs([va, vb], 1).freqs)
>>> Counter({'a': 2, 'c': 2, 'b': 2, 'e': 1, 'f': 1})
```
I updated the behavior so that now it produces the expected output: 
```
va = torchtext.vocab.Vocab(Counter('abbccc'))
vb = torchtext.vocab.Vocab(Counter('eeabbcccf'))
print(merge_vocabs([va, vb], 1).freqs)
>>> Counter({'c': 6, 'b': 4, 'a': 2, 'e': 2, 'f': 1})
```
I also added an extra test in `test_preprocess.py` to check this …

Fix IO.merge_vocab()

---

onmt/Loss.py
onmt/Trainer.py
onmt/modules/CopyGenerator.py

This PR reworks the `*LossCompute`  interfaces,  mainly addressing:
- removed the `forward()` interface from the base class.
- removed `copy_attn` knowledge from the base class. This moves the `make_shard_state()` interface to each subclass.  The subclass implements its own `compute_loss()`, whose interface corresponds to the return values of `make_shard_state()`, so it makes sense to implement `make_shard_state()` for each subclass.
- added a `monolithic_compute_loss()` for computing the loss monolithically, compared to `sharded_compute_loss()`, which computes the loss in shards.
- removed the `**kwargs` arg in the subclass's  `compute_loss()` interface. This make the subclass's interface concrete and explicit for what they want.
Now the new interface in `Loss.py` is totally agnostic to …

LossCompute rework

---

opts.py
train.py
translate.py

This PR is trivial:
-  Turn off multigpu for `train.py` for now, error message will be spewed if user specify multiple gpu ids.
This temporarily fixes https://github.com/OpenNMT/OpenNMT-py/issues/323.
-  Turn off `-batch_size` for `translate.py` for now,  it will be set to 1 and a warning is printed.
-  Move the options declaration in `translate.py` to `opts.py`, as like preprocess and train.

Turn off multigpu for train and batch_size for translate

---

onmt/ModelConstructor.py
onmt/Trainer.py
train.py

It is preparation for the Optim refactor work.  The `noam` learning rate decay formula has a `rnn_size` factor in it, but since we now have `transformer` and `cnn`, it is ambiguous to use `rnn_size`. So this PR
adds `transformer_size`, `transformer_hidden_size` and `transformer_head_count` for `transformer`,  and adds `cnn_size` for `cnn`. They will not use `rnn_size` anymore. Assertion failure will be thrown if users use them with `rnn_size`. Also group the options for each model in `opts.py`.
**Patch list**
1. d7571b5 Transformer: add its own options for fine tuning
It adds the aforementioned options, also adds assertion for the size match with `[src_|tgt_]word_vec_size`. It now asserts failure if user use `rnn_size` for `transformer`.
2. e3fb909 Conv2Conv: add its own options for fine …

Make transformer and cnn use their own commandline options instead of using rnn_size

---

onmt/modules/SRU.py
requirements.txt

Running the commands in the README.md fail with the following message: `ValueError: lengths array has to be sorted in decreasing order`.  Forcing `torchtext==0.1.1` resolves the issue.

Fix issue #368 by forcing torchtext 0.1.1

---

onmt/ModelConstructor.py

This PR fixes #341, a silly bug due to typo, but hasn't been noticed for quite long.

RNNEncoder:  fix "mistake dec_layers as enc_layers" bug

---

onmt/Models.py

Current version of OpenNMT crashes when using `GRU` in `StdRNNDecoder`. This is happening because the input to forward are different for [GRU](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L399-L405) as compared to [LSTM](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L322-L330). This PR accounts for the variation in input.
Command to run `GRU` version:
```
python train.py \
-data data/demo \
-save_model demo-model \
-enc_layers 1 \
-dec_layers 1 \
-epochs 4 \
-rnn_type GRU \
-input_feed 0 \
-batch_size 4
```

Modify forward pass of rnn for GRU

---

opts.py

`-brnn` wasnt really deprecated in that the flag was still existing but useless. It's really confusing as user has no way to know about this deprecation. 
Just removing the flag isn't a really good solution either because it does not provide a solution. I added an action in opts.py for argparse so that the flag, when set, raise an error with a message (provided in help) so we can point users to the correct usage.

Raise error for deprecated opts

---

onmt/modules/SRU.py

In python 3.5, num_block is being returned as a float type, which throws an error in the forward and backward compute functions. I simply changed it to explicit integer division to ensure the correct type is returned.

 Fix unintended float type for num_block in SRU.py

---

preprocess.py
train.py
translate.py

This is a small change related to CLI user experience.
1. `-h` CLI option prints the default values assumed by the cli args
2. `{preprocess, train, translate}.py` files are made executable.
```
$python translate.py -h
....(truncated)... 
optional arguments:
-h, --help            show this help message and exit
-md                   print Markdown-formatted help text and exit.
-model MODEL          Path to model .pt file
-src SRC              Source sequence to decode (one line per sequence)
-src_img_dir SRC_IMG_DIR
Source image directory
-tgt TGT              True target sequence (optional)
-output OUTPUT        Path to output the predictions (each line will be the
decoded sequence
-beam_size BEAM_SIZE  Beam size
-batch_size BATCH_SIZE
Batch size
-max_sent_length MAX_SENT_LENGTH
Maximum …
```

FIX: Print default values of CLI args

---

onmt/IO.py
onmt/ModelConstructor.py
onmt/Trainer.py
onmt/Translator.py
preprocess.py
test/test_models.py
test/test_preprocess.py
train.py
translate.py

This pull request makes some changes to IO.py in order to make the Dataset creation process clearer and easier to extend. Changes are primarily these:
1. I removed almost all of `ONMTDataset`'s static methods. They now live in IO.py as normal functions. Static methods are not necessary very often, and I felt that here they were obscuring the purpose of the `ONMTDataset` class here.
2. I altered the constructor of the `ONMTDataset` so that it no longer takes `opt` as an argument. Although this results in having to pass in more arguments, I think it is better to be explicit.
3. I consolidated the functionality of the various iterators over the data files. The process is now taken care of in the `read_corpus_file` generator.
4. I included an assertion in `ONMTDataset` that the `src_img_dir` …

Refactor dataset

---

onmt/modules/ConvMultiStepAttention.py

The fully convolutional model has used attention in a wrong way.
The shape of `pre_attn` is `[bs, dec_seq, enc_seq]`
And according to https://github.com/pytorch/pytorch/issues/1020 the softmax is done over dimension 0, whereas it should be done over dimension 2.

Fix fully CNN model attention

---

onmt/Models.py

If isinstance(enc_hidden, tuple), it should be an LSTM instead of GRU. The original comment is confusing.

correct comments

---

onmt/Translator.py
opts.py

We have had the GlobalScorer for a while (code is in Beam.py) that activates the Wu et al. length and coverage penalty. So far we had to manually activate it. I added two options in opts.py that we can use now. 
With this PR, the default behavior remains unchanged.

Activate Globalscorer through options

---

onmt/Models.py
onmt/Translator.py
onmt/Utils.py
onmt/modules/GlobalAttention.py
test/test_attention.py
translate.py

These changes correctly mask illegal attention weights during translation. It could easily be extended for training when source batches with variable lengths are required but it is not applied for now.
Fixes #272.
Fixes #318.

Fix batch translation

---

tools/embeddings_to_torch.py

Easily plug GloVe pre-trained embedding into OpenNMT-py.    
*the script is a slightly modified version of [ylhsieh's one](https://github.com/ylhsieh/OpenNMT-py/blob/efec98f4ad3b3b16d2a23ce61aa9a9ba37182052/embeddings_to_torch.py).*
**Usage:**
```
usage: embeddings_to_torch.py [-h] -emb_file EMB_FILE -output_file OUTPUT_FILE
-dict_file DICT_FILE [-verbose]
```
* `emb_file`: GloVe like embedding file i.e. CSV `[word] [dim1] ... [dim_d]`
* `output_file`: a filename to save the output as [PyTorch serialized tensors](http://pytorch.org/docs/master/torch.html?highlight=save#torch.save)
* `dict_file`: dict output from OpenNMT-py preprocessing
**0) set some variables:**
```
export data="../onmt_merge/sorted_tokens/"
export root="./glove_experiment"
export glove_dir="./glove"
```
**1) get GloVe …

New tool: embeddings_to_torch

---

onmt/Optim.py
opts.py
train.py

onmt/Optim.py.
Change it from the value 0.98
(earlier adopted from "Attention is all you need"
https://arxiv.org/pdf/1706.03762.pdf)
to the more widely established value of 0.999
which was sugggested in the original paper about Adam
https://arxiv.org/pdf/1412.6980.pdf.
The new value of 0.999 is still being used by default in the main nmt architectures
and frameworks, including tensorflow and kerras.
https://www.tensorflow.org/api_docs/python/tf/train/AdamOptimizer
https://keras.io/optimizers/
modified:   onmt/Optim.py

Changed the value of the parameter value of the Adam optimizer beta2 in

---

.travis.yml
onmt/IO.py
opts.py
preprocess.py
test/pull_request_chk.sh
test/test_preprocess.py
translate.py

As #380 is merged, the `ONMTDataset` is becoming unwieldy to read and maintain, and it also has conflict with the preprocess sharding work in  #384.
This PR just factors out the giant `ONMTDataset`  into `TextDataset`, `ImageDataset`, and `AudioDataset` (all are subclasses of `ONMTDatasetBase`), and I also factors out the preprocess skeleton, with some handy helper functions added.  I also cleans up `onmt/IO.py` a little bit,  with some docs updated/added.  
Besides, `test/pull_request_chk.sh` is updated to include the `im2text` and `speech2text` tests.

Dataset separation

---

onmt/Trainer.py
onmt/io/IO.py
onmt/io/TextDataset.py
onmt/io/__init__.py
opts.py
preprocess.py
test/pull_request_chk.sh
test/test_preprocess.py
train.py

**The problem**
This PR addresses the `preprocess.py` memory hogging problem. Currently it loads in the whole corpus file to create `onmt.IO.ONMTDataset`(which is subclass of `torchtext.data.Dataset`). So if the corpus file is too large, it will eat up large amount of memory(Using python generator trick for lazy load doesn't help, if `filter_pred` is not None, the dataset creation code will iterate over whole file to filter, which loads in the whole corpus too). 
**The method and implementation**
This PR adds a `max_shard_size` option, which indicates the size of a shard, and  the corpus file will be divided into shards of this size, and create `onmt.IO.ONMTDataset` separately and each dataset is written to disc as it is created to avoid this memory hogging problem. And at training time, …

Preprocess sharding work

---

tools/embeddings_to_torch.py

Try to fix #470.
When there exist some word features, the list `vocabs` will contain more than 2 elements. Only the first one and the last one are "word" vocabulary and can be matched with a pre-trained "word" embedding model.
Anyway, not sure whether this is a good way to fix it.
Using pre-trained embedding for word features such as POS tag is also quite reasonable.
Saving encoder, each word feature, and decoder vocabulary separately can be a better solution, though this requires running the script for (# vocabularies) times.

Fix tools/embeddings_to_torch.py for #470

---

.travis.yml
onmt/io/AudioDataset.py
onmt/io/DatasetBase.py
onmt/io/IO.py
onmt/io/ImageDataset.py
onmt/io/TextDataset.py
onmt/io/__init__.py
preprocess.py
test/test_preprocess.py

This PR addresses #466.
Basically, after this further refactoring, the `IO.py` now just acts as a dispatcher and delegates work to specific `*Dataset`'s static methods.
Furthermore, I create a new `onmt/io/DatasetBase.py` to lodge `ONMTDatasetBase`, which could avoid the import circular dependency problem between `IO.py` and `*Dataset.py` ( Before this, `*Dataset` uses `IO.py`'s `ONMTDatasetBase`,  while `IO.py` uses `*Dataset.py`'s `*Dataset`, which will create a circular import problem).  And this separation seems good, it naturally de-entangles things and exposes more cleanup opportunities.

Further IO refactoring

---

docs/source/options/translate.md
opts.py
requirements.opt.txt
requirements.txt
tools/test_rouge.py
translate.py

Hi, I find it's tedious to run perl scripts to test bleu after I run ```python translate.py```,  and I also find the 'Example: Summarization' uses files2rouge, which cannot be set up in my python3 environment. So I insert ```report_bleu``` and ```report_rouge``` (which depends on pyrouge) into ```translate.py```. For testing rouge  I write a simple script(```tools/ test_rouge.py```) to use pyrouge. And the last thing is that I add -report_bleu & -report_rouge in ```opts.py```

Add a Bleu/Rouge report during translation

---

onmt/translate/Beam.py
onmt/translate/Translator.py
opts.py
translate.py

As we discussed in https://github.com/OpenNMT/OpenNMT-py/issues/457 we may want to force a minimum length for prediction by manually decreasing eos score for decoding step < min_length.
I set the option default on 0.

Minimum prediction length at translation time

---

onmt/Trainer.py
onmt/io/DatasetBase.py
onmt/io/IO.py
onmt/io/TextDataset.py
onmt/modules/CopyGenerator.py
preprocess.py
test/test_preprocess.py
train.py

This PR is supposed to supersede #504.
It does two things:
- fix the preprocess sharding memory issue, as is done in #504.
- implement train side lazy dataset load, but keeping the interface as the same, and making the code easy to read.
**Changes for train side lazy dataset load:**
- `load_dataset()`  now actually just return dataset lazy loader, and dataset is loaded when really needed.
- `load_fields()` now literally loads `fields`, setting it to dataset is postponed to the point when dataset is loaded.
- A new `make_dataset_iter()`, which hides the facts of multiple datasets , and lazily load dataset and creates `DatasetLazyIter` for each dataset.
- `Trainer` code is almost the same as old, except:
- `train_loss/valid_loss`'s `dataset` attribute is also lazily set to current dataset …

Fix preprocess sharding and implement train side lazy dataset load

---

train.py

The variable 'fields' contains 'src_map' key. It's filtered out, because it is not present in the dataset. 
When training from a checkpoint 'fields' variable is loaded twice. But 'src_map' is filtered out only after the first load. 
I suggest a change where fields is loaded only once.

Fix the error caused by the field "src_map" in fields, when training from a checkpoint

---

train.py

#517 was not properly fixed for conflict.  This PR cleans it up.
Now that we pass in data_iter on every epoch, no need to do the load before the training. So remove that part of code.  Now we only need to load first dataset to determine `data_type` before the training.
Besides, let lazily_load_dataset() return dataset files in increasing order of index.

train: cleanup

---

onmt/io/TextDataset.py

Since torchtext no longer automatically allocates an UNK token when initializing a vocab object, we need to explicitly set it.

specials in dynamic_dict

---

onmt/Loss.py
onmt/modules/CopyGenerator.py
opts.py
train.py

The main part of this PR introduces an option `copy_loss_by_seqlength` which changes the behavior of the loss when using `copy_attention`.
Normally we are computing the loss per token in a batch (zeroing out padding). Then the loss was computed as the average loss per batch. So, if the `loss` is a tensor with all individual token losses, the total loss is computed as
`loss.sum().div(batch_size)`
With `copy_loss_by_seqlength`, the loss is computed such that the loss is first divided by the length of its sequence. Let `loss` be a `batchsize x seqlength` tensor and `tgt_lengths` the actual lengths in the target without padding. Then, the loss is computed as 
`loss.div(tgt_lengths).sum().div(batch_size)`.
Example: 
Loss:
| 1  | 2 |
| ------------- | ------------- |
| 1  | 0  |
tgt_lengths:
| …

Adding comments to copyCriterion and introduce option for more advanced copy loss

---

tools/embeddings_to_torch.py

Related to: http://forum.opennmt.net/t/using-word2vec-embeddings-in-onmt-py/1331 
I suggest using the new option `-type word2vec` (that just skip the first line) to load word2vec text embeddings. 
This does not support binary version of word2vec tho.

Support word2vec text embedding format

---

translate.py

Hi,
When running translate.py from another directory, the relative path "tools/multi-bleu.perl" is not correct, and calling the script fails. Same for Rouge. I suggest to get the path of the translate.py script and assuming the tools are at the same place, but there might be better ways to handle this...

add path to rouge/bleu script calls

---

onmt/io/ImageDataset.py

White color is (1,1,1) after running transforms.ToTensor(), so padding with 1 is more reasonable.

Fix image padding

---

tools/embeddings_to_torch.py

Fixed the following error when executing the script ./tools/embeddings_to_torch.py
```
Traceback (most recent call last):
File "./tools/embeddings_to_torch.py", line 124, in <module>
main()
File "./tools/embeddings_to_torch.py", line 87, in main
enc_vocab, dec_vocab = get_vocabs(opt.dict_file)
File "./tools/embeddings_to_torch.py", line 24, in get_vocabs
assert None not in [enc_vocab, dec_vocab]
File "/home/xing/anaconda3/envs/pytorch-new/lib/python3.6/site-packages/torchtext/vocab.py", line 75, in __eq__
if self.freqs != other.freqs:
AttributeError: 'NoneType' object has no attribute 'freqs'
```

Fixed NoneType error in ./tools/embeddings_to_torch.py get_vocabs

---

README.md

OpenNMT keeps getting turned into Opennmt.

Improve BibTeX capitalization

---

onmt/Loss.py

in pytorch 0.4 version. Call .dim() on a null tensor will also
return 1, which will trigger bugs when unsing index_fill_
afterwards.

fix bugs when using label smoothing.

---

.gitignore
onmt/translate/Translator.py

This pull ensures that `-report_bleu` flag is working properly. It also includes some path check for both `_report_bleu` function and `_report_rouge`.
regarding `.gitignore` change, it seems very dirty to place the checkpoint into the original directory. That's why it could be better if we use some folder to save our model, logs and prediction files into those folders.

Fix : -report_bleu issue

---

onmt/decoders/decoder.py
onmt/decoders/transformer.py
onmt/modules/global_attention.py
onmt/opts.py
onmt/translate/translator.py
onmt/utils/misc.py

This PR adds a new batched beam search implementation that is up to 7x faster than the current implementation. This is made possible by batching all operations, in particular the batch reordering and TopK, which results in an overall better GPU usage.
However, this new code path does not support all decoding features. Here, I'm suggesting to add a `-fast` translation flag and raise an `AssertionError` on incompatible options. A typical goal would be to migrate all existing features to this new implementation (without impacting the speed if they are not enabled).
Here are some numbers from the pretrained models available on the website. The translation was executed on a GTX 1060 with the following options:
```text
-batch_size 32 -beam_size 4 -gpu 0
```
|  | Time to translate (s) | BLEU …

Faster batched beam search

---

onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/model_builder.py
onmt/modules/position_ffn.py
onmt/opts.py
onmt/tests/output_hyp.txt
onmt/trainer.py

This is urgent for the fix in trainer.py (typo)
otherwise it just adds the heads / transformer_ff options (to train a big transformer for instance)
config for base:
-word_vec_size 512 -rnn_size 512 -heads 8 -transformer_ff 2048
config for big:
-words_vec_size 1024 -rnn_size 1024 -heads 16 -transformer_ff 4096

add options to transformer (heads, transformer_ff) + fix typo trainer.py

---

onmt/decoders/cnn_decoder.py

The "step" parameter is missing in the CNNDecoder.forward function. And to keep the compatibility, I add the "step" parameter and fix it.

Add a parameter "step=None" to the CNNDecoder.forward function.

---

onmt/tests/test_models.sh

The command:
```
./test_models.sh set_all_gpu [...]
```
uses every GPU set in `CUDA_VISIBLE_DEVICES`.
It wasn't working because of comma-separated list of GPUID (instead of space) and double-quotes making it a single argument instead of a list.

fix 'set_all_gpu' in 'test_models.sh'

---

onmt/utils/logging.py
train.py

First, Commit d36316e10e92bd0196d050978cb893dcda1464d7 was meant to fix logging for multi-device setup. In this case, `init_logger` was called in `train.py`, then, sub-process would print.
In order to fix that, we should've **moved** tje `init_logger` from train.py to `train_single.py`, but instead, it has been duplicated.
This problem has been discussed in https://github.com/OpenNMT/OpenNMT-py/pull/821 (which is replaced by this PR).
----
In addition, I remove `addHandler` in order to avoid output duplication.

Removing extra logger initiatilzation

---

onmt/translate/beam.py

Block_ngram_repeat is invalid. Notice that line 118 in beam.py  will never be triggered.
```
if tuple(gram) in ngrams:
fail = True
```
It is because torch.tensor is not compatible with set() in python.
Look at the following code:
```
a = torch.tensor(1)
b = set()
b.add(torch.tensor(1))
print (a in b)
```
the result is false.
I think an elegant way of solving the problem is using .item() to transform tensor to number in python.

Fix the error in block ngram repeat 

---

onmt/decoders/cnn_decoder.py
onmt/decoders/decoder.py
onmt/decoders/transformer.py
onmt/modules/embeddings.py
onmt/modules/multi_headed_attn.py
onmt/translate/translator.py

This is an implementation of the transformer decoder cache.
As it is only beneficial for the fast beam search (thanks @guillaumekln!), its use is conditioned to the `-fast` option.
For 3k segments (WMT EN-DE 2014, sorted) on a GTX 1080:
BATCH 32 - BEAM 5
- fast beam: 77 seconds (peak VRAM usage 7.9G)
- fast beam + cache: 65 seconds (peak VRAM usage 2.4G)
BATCH 32 - BEAM 10
- fast beam: 137 seconds (peak VRAM usage 7.9G)
- fast beam + cache: 114 seconds (peak VRAM usage 3.7G)

Add decoder cache on top of fast beam search for transformer

---

onmt/translate/translation_server.py

1. Allow boolean options (such as `-fast`) to be used in model config.
2. Fix handling of whitespaces in segments

Small fixes to rest server

---

onmt/decoders/transformer.py
onmt/modules/global_attention.py

In GlobalAttention class, it is documented that `forward` method takes `input` parameter.
```
class GlobalAttention(nn.Module):
...
def forward(self, source, memory_bank, memory_lengths=None, coverage=None):
"""
Args:
input (`FloatTensor`): query vectors `[batch x tgt_len x dim]`
memory_bank (`FloatTensor`): source vectors `[batch x src_len x dim]`
memory_lengths (`LongTensor`): the source context lengths `[batch]`
coverage (`FloatTensor`): None (not supported yet)
Returns:
(`FloatTensor`, `FloatTensor`):
* Computed vector `[tgt_len x batch x dim]`
* Attention distribtutions for each query
`[tgt_len x batch x src_len]`
"""
```
However, it actually takes `source` parameter. So the code below would produce an error.
```
>>> attn = onmt.modules.GlobalAttention(
dim=hidden_size, …
```

Fix parameter docs

---

docs/source/im2text.md
onmt/opts.py
onmt/train_single.py

Hi!
I've updated the markdown file of the im2text example to reflect the changes commented in #672 (-tgt_seq_length  150 and -tgt_words_min_frequency 2) as well as two changes that [your paper](https://arxiv.org/pdf/1609.04938.pdf) points out (-word_vec_size 80 and -beam_size 5) but are not reflected in the web.
Luckily I found the issue early on, but it has been a pity finding out the other two changes after performing all the tests. So let's make sure I'm the last one having that problem
**EDIT:** Also, according to the paper the encoder LSTM has to be bidirectional, which is not by default

Updated im2text docs

---

onmt/translate/translation_server.py

This PR aims to allow passing pyonmttok options directly in the models config file (`available_models/conf.json`).
(Thanks @guillaumekln for the advice.)
For now, I kept "model" in mandatory ([#L230](https://github.com/francoishernandez/OpenNMT-py/blob/245ef7c311d42e38a2178306e450d6e1515e8771/onmt/translate/translation_server.py#L230)) because it may be a useful warning, but the model (bpe for instance) is passed in `"params"` for pyonmttok. A solution would be to change the behaviour of the sentencepiece option, or remove it at once and only allow pyonmttok.
Any thoughts, @guillaumekln @vince62s @pltrdy @srush ?
Example:
```
{
"models_root": "directory_containing_models",
"models": [{
"id": 1,
"name": "my_model",
"model": "my_model.pt",
"timeout": 15,
"load": false,
"on_timeout": …
```

handle pyonmttok options in server config

---

onmt/translate/translation_server.py

This fixes some unwanted behavior in handling whitespaces and empty segments when querying the rest server.
The code is also easier to understand (I think).
Basic idea is : we split inputs in heading whitespaces, input text, and tailing whitespaces and only send non empty input texts to the translator. This allow to handle seemlessly empty or 'whitespaces-only' segments -- and preserve heading and tailing whitespaces also.

Fixed and simpler whitespace handling in rest server

---

onmt/trainer.py
train.py

fixing a bug introduced in the recent refactoring.

Fix bptt cf #891

---

onmt/inputters/text_dataset.py

This pull request is a quick fix for #911, which is caused by the fact that explicitly raising `StopIteration` is no longer merely frowned upon, but actually raises an error now. All `raise StopIteration` lines have been converted into bare returns.

Do not explicitly raise StopIteration

---

onmt/translate/translation_server.py
server.py

When using `threaded` mode with Flask (that we now explicitly set*), we found that multiple requests on unloaded models results in loading the model multiple times in parallel.
----
(*) some previous flask versions are not threaded by default

[TranslationServer] Mutually exclusive model loading

---

onmt/utils/distributed.py

Changing the fixed tcp port 10000 to a random one (10000~20000), which could avoid port collision  during running several training tasks on multiGPU.

Set Random Port for Torch Distributed Nccl backend.

---

onmt/inputters/inputter.py
onmt/modules/copy_generator.py
onmt/trainer.py

Fix #746 
@srush @JianyuZhan I don't really know why the get_cur_dataset() was needed at one point in time.
All I can say, it is not used in the code except in the training loop, but we can remove it since the batch object embeds the current dataset.
It also fixes the case when we use collapse_copy_scores (because copy_attn) with the accum_count option and sharding. see #746

Remove need for cur_dataset attribute in the loss class (inherent to batch)

---

onmt/modules/embeddings.py

OpenNMT-py requires input embedding size ( word_vec_size ) equals to pretrained embedding size. I relax this constraint: (1) If word_vec_size > pretrained_size, we initialize part of input embedding layer, and the rest is uninitialized. (2) If word_vec_size < pretrained_size, we use the truncated pretrained vector for initialization.
Relaxing above constraint has the following advantages:
1. It is common that we only have 300d pretrained vectors, but the default d_model of transformer is 512. And 300%8 != 0, where 8 is the default number of self-attention head. The transformer can not utilize pretrained vectors before the change.
2. We witness the better performance by initializing part of input embedding layer, i.e. the setting (word_vec_size=500, pretrained_size=300) performs much …

Relax the constraint: word_vec_size must equal to pretrained_size

---

tools/test_rouge.py

test_rouge function takes iterator as parameter since b8d807.
Thus we need to provide opened files instead of path.
* Fixes: https://github.com/OpenNMT/OpenNMT-py/issues/953

[FIX] Open files in test_rouge.py

---

onmt/translate/translation_server.py

`ServerModel.load()` in translation server mutates `self.tokenizer_opt["params"]` by prepending `self.model_root`. This yields the correct path after the first call to `load`, but on subsequent calls the model root is duplicated. Multiple loading occurs e.g. after a model is unloaded on timeout.
The proposed fix mutates a temporary copy of the parameter dict.

model_root prepended multiple times if model is reloaded

---

onmt/inputters/image_dataset.py

`opencv-python` is currently in `requirements.opt.txt` (which is a good thing imo) but `import cv2` is not optional, thus it raises `ImportError`.
I suggest moving the import into the function that uses cv2.

Do not import 'cv2' by default (to keep 'opencv-python' it optional)

---

onmt/model_builder.py
onmt/opts.py
onmt/utils/optimizers.py

#970 #768
Idea is as follow: new option along with train_from: -reset_optim
default: 'none' training will just continue (optim loaded from checkpoint, steps same, states loaded)
'all': reset completely the optimizer. it requires to pass a full set of settings (train_steps from zéro, type of optim, ....)
'states': it will load everything from the checkpoint except Adam states that will be reset.
'keep_states": it will load Adam states from the checkpoint but take into account command line changes (egs: learning_rate)
if someone can test, would be good. @wewark ? guys in #768 ?

[WIP] Ability to reset optimizer or just its states

---

tools/test_rouge.py

Regex string must be prefixed by 'r'. 
Not using prefix is deprecated in python 3.6, therefore, `flake8 3.6` would raise a `W605`.

Use regex prefix

---

onmt/inputters/inputter.py
tools/create_vocabulary.py

This PR addresses the issue #945 (and possibly #989?). Instead of ignoring tokens that are not present in the current corpus, it keeps all the tokens referenced in the vocab path and also in the specified order of said file.
A new script is also added to the `tools` directory - `create_vocabulary.py`. This script allows to take a previously preprocessed corpus' `*.vocab.pt` file or a corpus text file (or several) and create a vocabulary file to use in the preprocessing stage.

Change how existing vocabularies are loaded in preprocessing

---

onmt/inputters/inputter.py

I am using OpenNMT-py for English-Japanese translation with Python 2.
In the load_vocabulary function, the vocabulary file is opened without codecs.  This causes that the vocabulary including non-ascii characters does not match with the words in the text because Python 2
distinguishes raw strings and unicode strings.  (This phenomenon is only caused in Python 2.  In Python 3, two strings match.)
I request to fix this problem by using `codecs.open()` in the function.

Codecs in onmt.inputters.inputter.load_vocabulary() for Python 2

---

onmt/decoders/cnn_decoder.py
onmt/decoders/decoder.py
onmt/decoders/ensemble.py
onmt/decoders/transformer.py
onmt/translate/translator.py

This cleans up the `DecoderState` by using the generic `map_batch_fn` method.

Implement repeat and beam_update via map_batch_fn

---

docs/source/options/translate.md

Currently the documentation for [translate.py](http://opennmt.net/OpenNMT-py/options/translate.html) shows no options for -length_penalty and -coverage_penalty, although two variants are implemented for each.
This PR adds these options 
```
-length_penalty [none] Length Penalty to use. Options are [wu | avg]
-coverage_penalty [none] Coverage Penalty to use. Options are [wu | summary]
````

show penalty options in documentation of translation.py

---

onmt/decoders/cnn_decoder.py
onmt/decoders/decoder.py
onmt/decoders/ensemble.py
onmt/decoders/transformer.py
onmt/models/model.py
onmt/tests/test_models.py
onmt/trainer.py
onmt/translate/translator.py

This is necessary for future Onnx export.
This "simplifies" the way we maintain the decoder state within the Decoder itself.

Remove DecoderState Class (for future Onnx export)

---

onmt/decoders/transformer.py

This line wrongly overrides the returned `attns` variable.

Remove incorrect variable assignment

---

onmt/inputters/inputter.py

Currently while merging vocab when source and target vocabulary are shared, it only checks if max_vocab_size is consistent. However, if someone is trying to control for min_frequency this information is lost while merging. This pull request tries to fix that.

adding min frequency parameter in vocab merge

---

onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/model_builder.py
onmt/modules/__init__.py
onmt/modules/position_ffn.py
onmt/modules/util_class.py

The goal is to use the generic LayerNorm Class from Pytorch instead of the current adhoc class.
To maintain backward compatibility with existing model, we need to rename the state_dict:
a_2 => weight
b_2 => bias
(thanks @guillaumekln @pltrdy for pointing the changes)

Use legacy Pytorch LayerNorm

---

docs/source/options/train.md
onmt/modules/sparse_activations.py
onmt/modules/sparse_losses.py
onmt/opts.py

This pull request makes two changes:
1.  It incorporates Vlad Niculae's suggestions for improving the numerical stability of sparsemax.
2. It renames the default `-generator_function` option from `log_softmax` to `softmax`. It was inconsistent that the two options were called sparsemax and log softmax, given that both functions are passed through a log.

Improve numerical stability of sparsemax

---

onmt/decoders/ensemble.py
onmt/opts.py
onmt/translate/translator.py

This pull request adds a new option for computing scores for ensembled models. Previously, the only option was to average the log probabilities assigned by each model in the ensemble. This strategy is incompatible with models that output probability distributions that are not strictly positive because because the log of a zero probability is negative infinity, which breaks the averaging.
As an alternative, I added the command line option `-avg_raw_prob`, which will instead average the raw probabilities. Future work could explore other ensembling strategies such as majority voting.

Add option for averaging raw probabilities in ensembles

---

onmt/decoders/decoder.py
onmt/encoders/encoder.py
onmt/encoders/mean_encoder.py
onmt/encoders/rnn_encoder.py
onmt/train_single.py
onmt/trainer.py
onmt/translate/translation.py
onmt/utils/rnn_factory.py
tools/extract_embeddings.py
train.py
translate.py

This small PR removes `from __future__ import division` lines from scripts in which no integer division could plausibly occur. Unlike standard imports, future imports do not trigger flake8 when they are unused.

Remove unnecessary future division imports

---

onmt/utils/report_manager.py

* https://github.com/OpenNMT/OpenNMT-py/issues/1056
When `-train_from` is set, we directly use `-tensorboard_log_dir` for tensorbard logging instead of using a sub-dir based on training time (date + hour).

log tensorboard result after loading from checkpoint

---

onmt/opts.py
onmt/translate/translation_server.py
onmt/utils/logging.py

PR: https://github.com/OpenNMT/OpenNMT-py/pull/1062 changed the default behavior (i.e. logging everything to file when `-log_file` is set).
This revert the pre-1062 default behavior and introduce a flag `-file_log_level` in order to set it. 
Both level and numerical values are accepted:
|Level	|  Numeric value|
|---|---|
|CRITICAL |	50 |
|ERROR |	40|
WARNING|	30
INFO|	20
DEBUG|	10
NOTSET	|0

Set file logging level with a new  option

---

onmt/modules/__init__.py
onmt/modules/copy_generator.py
onmt/modules/sparse_losses.py
onmt/utils/loss.py

This pull request makes a number of small changes intended to make the behavior of the loss code easier to understand and extend.
1. `SparsemaxLoss` now takes a `reduction` parameter similar to that used by `nn.NLLLoss` and `nn.CrossEntropyLoss`.
2. The `CopyGeneratorCriterion` class, which did not subclass `nn.Module`, is replaced by `CopyGeneratorLoss`, which does. The code for computing the loss has been made simpler, although this is still a work in progress. In particular, it would be nice if the `CopyGeneratorLoss` had a similar reduction parameter to other loss modules. I do not like that the loss computation for copy models is divided between two places, the criterion module and the `_compute_loss` method of `CopyGeneratorLossCompute`. For other module types, the loss computation …

Make loss code more uniform across model types

---

onmt/translate/translator.py

This PR fixes `-attn_debug` option for `-fast` mode. It seems that `-attn_debug -fast` is conditioned with `-replace_unk`, which is unnecessary in my understanding.
Specifically, `def translate_batch` from `onmt/translate/translator.py` calls `def _fast_translate_batch` with `return_attention=self.replace_unk`. Therefore, enabling `-attn_debug -fast` without using `-replace_unk` ends up returning no attention, which raises an error at the `if attn_debug` block.
I suspect that original intention here was making `-replace_unk` dependent of `-attn_debug`, but `-attn_debug` itself should be a standalone option. How do you think @guillaumekln ?
(btw, thanks for refining the previous PR!)

Fix attention option when using fast beam search 

---

onmt/decoders/cnn_decoder.py
onmt/decoders/decoder.py
onmt/decoders/ensemble.py
onmt/decoders/transformer.py
onmt/translate/translator.py

Both translation paths now set `with_cache=True` (non fast beam search had to wait for https://github.com/OpenNMT/OpenNMT-py/commit/9fef5b223067fc92eb4dae34caf5d4d8ac2683e3 which added batched gathering of the decoder state), so let's cleanup the Transformer state to reflect that.

Only cache projections in Transformer state

---

docs/source/Summarization.md

After running into the same issue as https://github.com/OpenNMT/OpenNMT-py/issues/476 when computing the validation scores, reducing the validation batch size just solved the problem.

reduce valid batch size in summarization tutorial

---

server.py

fixes: `argparse.ArgumentError: argument -config/--config: conflicting option string: --config`    when starting `server.py`.

Remove config_opts from server

---

onmt/inputters/inputter.py
onmt/opts.py
preprocess.py

These changes related to the behavior when preprocessing the validation data. Previously, the validation data would be filtered by length and there was no way to change this option. This PR makes it so that by default the validation data is _not_ filtered unless preprocess.py is called with `-filter_valid`, in which case the validation is filtered with the same parameters as the train set.
The PR also very slightly changes the meanings of certain parameters of `filter_example` which were misnomers, and gives `build_dataset`'s filtering-related parameters more sensible defaults.

Do not filter validation data by default

---

preprocess.py

Handful of times I've preprocessed train files correctly only to realize at a later point that my path to valid files were wrong, do file exists check early on! Minor nit

Exit early if src/tgt files do not exist

---

onmt/modules/multi_headed_attn.py

I observed that certain things like linear_keys, shape(..) are scattered throughout the multi headed attention file.

Simplify multi headed attention

---

onmt/models/model.py
onmt/trainer.py

Making behavior consistent with earlier behavior for truncated bptt like in [v0.1](https://github.com/OpenNMT/OpenNMT-py/tree/v0.1). The state of decoder is saved and restored in the next bptt instance.

fix for Not restoring state correctly during truncated bptt #1164

---

onmt/inputters/__init__.py
onmt/inputters/inputter.py
onmt/model_builder.py
onmt/train_single.py
tools/extract_embeddings.py

This pull request fixes two related bugs that occurred when attempting to load a dataset or model that uses copy attention and was preprocessed or trained before #1132 was merged. 
The issue was related to a difference in how fields are constructed. Before #1132, copy attention-specific data like `src_map` and `alignment` was created whenever fields were initialized, whether they were actually necessary or not. #1132 changed that default behavior, but failed to correctly indicate if the copy attention fields were necessary when loading fields from old-style vocab lists. The correct fields should be made now.

Fix 1168 and 1170

---

onmt/opts.py

This PR makes it possible to specify the `tensorboard_log_dir` in a config file. Previously, this caused an error.

Allow -tensorboard_log_dir to be set in config file

---

onmt/utils/optimizers.py

Note: it is still reset with `-reset_optim all`.

Do not reset LR scheduling step with -reset_optim keep_states

---

onmt/inputters/audio_dataset.py
onmt/inputters/dataset_base.py
onmt/inputters/image_dataset.py

Since there's no guarantee that a Dataset's ``make_examples`` class method is only called once, there should not be imports in it. Rather, they should be imported at the module level if possible and the dataset should make sure it has them if it needs them.
Originally part of  #1194

Smarter optional dependency imports in the datasets

---

onmt/inputters/text_dataset.py
onmt/modules/copy_generator.py

It's not clear that ``collapse_copy_scores`` belongs in the dataset. It seems that it's part of the statistics stuff in ``copy_generator.py`` so I moved it there. That's the only code that uses it AFAIK.
This was originally in #1194

Move copy scores from text dataset to copy_generator.

---

onmt/opts.py
onmt/utils/__init__.py
onmt/utils/misc.py
preprocess.py
translate.py

without running out of memory.
This PR uses the same mechanism as in preprocess.py
The use case is "Massive back translation"
When you need to translate millions of segments, you will run out of memory.
This PR will cut in shard_size chunks and translate sequentially.

Enable big file translation (for massive back translation)

---

onmt/inputters/audio_dataset.py
onmt/inputters/image_dataset.py
onmt/inputters/inputter.py
onmt/inputters/text_dataset.py
onmt/translate/translator.py

* Move ``inputters.make_img -> inputters.image_dataset.batch_img`` (no change other than renaming)
* Move ``inputters.make_audio -> inputters.image_dataset.batch_audio`` (no change other than renaming)
*Move ``inputters._feature_tokenize -> inputters.text_dataset._feature_tokenize`` (no change)
* Refactor ``get_fields`` to dispatch to the datatype's (new) fields function. The function takes arbitrary arguments so it's extensible without a case-like structure over the datatypes in ``get_fields``. It returns fields that are to be "top-level" (``src_lengths`` for audio) as well as ones that are scoped under the dataset's side (src/tgt).
Originally part of #1194

 Move batching and field logic from inputter to dsets

---

onmt/inputters/audio_dataset.py
onmt/inputters/image_dataset.py
onmt/inputters/inputter.py
onmt/inputters/text_dataset.py
onmt/translate/translator.py

Follow-up to #1196 per discussion on #1200 . I wasn't able to reopen 1196 since it's merged.
For text and img models, this restores backwards compatibility for checkpoints since #1132 . Audio models made between 1132 and now are not backwards compatible.
Backwards compatibility since 1132 was tested using the commands here: https://github.com/flauted/OpenNMT-py/issues/6 (check out master, preprocess, train and save, check out this, translate using the save).

Move batching and field logic from inputter to dsets

---

onmt/model_builder.py
onmt/modules/embeddings.py

In #950 , problem arises when training from checkpoint with fix_word_vecs. 
Reason: when loading checkpoint, the fix_word_vecs is ignored in https://github.com/OpenNMT/OpenNMT-py/blob/9c6e32a7e9b4c8a66af5c1b196bb0dc9886ef6ec/onmt/model_builder.py#L291 
So i move the fix_words_vec setting to embedding initialization.
Another way is to add specific check after load checkpoint:
```
if model_opt.fix_word_vecs_enc:
model.encoder.embeddings.word_lut.weight.requires_grad = False
if model_opt.fix_word_vecs_dec:
model.decoder.embeddings.word_lut.weight.requires_grad = False
```

Fix bug: error when training from checkpoint with fix_word_vecs

---

onmt/trainer.py

#1184 accidentally removed the line of code that updates the number of source words seen, which means that the statistics has been recording 0 target words per second. This PR restores that line.
Since there is no longer a check for `data_type` inside the trainer, I made `report_stats` update the number of source words if `src_lengths is not None`. This may have an unintended effect because audio models also have a non-none src_lengths. This may cause unnecessary source word logging when training a speech-to-text model, but I'm not sure if that is a problem.

Fix source word logging

---

onmt/utils/misc.py

This pull request fixes a bug in the behavior when shard_size is set to 0. The intended behavior, which this PR implements, is that data should not be sharded. What happened before was that the data never even got read at all.

Fix behavior with shard_size == 0

---

onmt/decoders/cnn_decoder.py
onmt/decoders/decoder.py
onmt/decoders/transformer.py
onmt/encoders/transformer.py

This PR makes a number of small changes to RNN, CNN, and transformer decoders. All of them had a number of attributes that were either completely unused or could be refactored away.
I noticed something strange in the transformer decoder implementation, which is that setting `-copy_attn` will cause the decoder to have a `GlobalAttention` module for copy attention, but this module was never actually used. What actually happens when one uses copy attention is that the context attention is used for copying. I removed the `GlobalAttention` module from the class.

Clean decoder code, remove unnecessary attributes

---

onmt/decoders/__init__.py
onmt/decoders/cnn_decoder.py
onmt/decoders/decoder.py
onmt/decoders/transformer.py
onmt/encoders/__init__.py
onmt/encoders/audio_encoder.py
onmt/encoders/cnn_encoder.py
onmt/encoders/encoder.py
onmt/encoders/image_encoder.py
onmt/encoders/mean_encoder.py
onmt/encoders/rnn_encoder.py
onmt/encoders/transformer.py
onmt/model_builder.py

This adds a ``from_opt`` constructor to all encoders and decoders and str2enc and str2dec dicts. It cleans up some of the logic in model_builder.py.

Add from_opt constructor to all encs/decs.

---

onmt/modules/embeddings.py
onmt/tests/test_embeddings.py

This also adds better input validation for the embedding module.

Add unit tests for embeddings module

---

onmt/trainer.py
onmt/utils/loss.py

The removal changed the memory requirements of the training which could possibly break existing user configurations.
This also reintroduces the unwanted side-effect that the loss computation initiates the backward pass unless max_generator_batches is 0.

Reintroduce partial backward if max_generator_batches > 0

---

onmt/trainer.py

* The outer `while steps <= train_steps` is not useful as the dataset yields an infinite iterator
* Multi-GPU sharding and batch accumulation can be expressed in terms of iterator wrappers

Simplify the training loop

---

onmt/tests/test_beam.py
onmt/tests/test_beam_search.py
onmt/translate/beam.py
onmt/translate/beam_search.py
onmt/translate/penalties.py
onmt/translate/translator.py

**This changes default behavior**!
1) The old master, slow code length penalty returns the *actual* logprobs (penalties.py L80) and the GlobalScorer changes it in place (beam.py L215). That's almost certainly not intended since the other length penalties don't change the probs in place. (**Fixed Master** below slows the scores when you change penalties.py L80 to read ``return logprobs.clone()``).
2) The old master, fast code would always use the Wu length penalty (with default ``alpha=0``, so None in the default case). Now ``-length_penalty`` must be specified for that behavior (see **This** below).
Most of the scores below are boring. The bolded names show the interesting ones. The slow coverage penalty scores change (both stepwise and not) because of (1). The fast length penalty …

Refactor, integrate penalties and global scorer into fast translation

---

onmt/models/model_saver.py
onmt/train_single.py
onmt/trainer.py

In particular, the trainer should always save a checkpoint on the last iteration. This PR also adds support for "-save_checkpoint_steps 0" to only save the last checkpoint.

Let the trainer decide when to save checkpoints

---

onmt/inputters/inputter.py
onmt/models/model_saver.py
onmt/opts.py
onmt/train_single.py
onmt/trainer.py
onmt/utils/statistics.py

I propose a new option `-single_pass` to iterate only once on the dataset. This enables meta training scripts to run the training epoch by epoch, and run arbitrary post-epoch processing such as translation, scoring, etc. In the case of multi-GPU training, we ensure that the total number of batches is a multiple of `opt.accum_cout * opt.world_size` by possibly looping over the dataset.
This also adds support for `-train_steps 0` to iterate on the dataset iterator until exhaustion (which could also be useful for early stopping). With #1272, this combination is now supported:
```text
-save_checkpoint_steps 0 -train_steps 0 -single_pass
```
which means "iterate on the dataset once and save the last checkpoint".

Training option to iterate on the dataset once

---

onmt/models/model_saver.py
onmt/opts.py
onmt/trainer.py

This is in attempt in following the logic implemented in [Marian NMT](https://github.com/marian-nmt/marian) - http://www.aclweb.org/anthology/P18-4020.
- we keep the moving average parameters on the GPU (around 500~600MB for base models);
- leads to ~5% speed decrease if we average every step. 
Features:

Moving average of model parameters

---

requirements.txt

For some reason, the [latest version of the tqdm package](https://github.com/tqdm/tqdm/releases/tag/v4.31.0) is causing issues when run inside Travis. Let's freeze the required version until there is a good reason to update this package.

Freeze tqdm version

---

onmt/inputters/__init__.py
onmt/inputters/audio_dataset.py
onmt/inputters/dataset_base.py
onmt/inputters/image_dataset.py
onmt/inputters/inputter.py
onmt/inputters/text_dataset.py
onmt/translate/translation.py
onmt/translate/translator.py
preprocess.py

The various [Datatype]Dataset's are just shells that define a ``sort_key`` static method. Since ``torchtext.data.Dataset`` only uses the ``sort_key`` attribute attached to the instance ``self`` (despite defining it at the class level) , we can just make the ``sort_key`` an instance attribute of the ``DatasetBase``. Consequently ``DatasetBase`` is now a general ``Dataset``. After this PR, the file dataset_base.py should be renamed to dataset.py.

Remove non-base datasets.

---

onmt/tests/test_beam.py
onmt/tests/test_beam_search.py
onmt/translate/beam.py
onmt/translate/beam_search.py
onmt/translate/penalties.py
onmt/translate/translator.py

Per discussion on #1268 .
All the slow/fast scores are matching. There's also some better validation of the coverage params. This fixes #994 since the scores don't line up unless that's fixed. That makes the slow code appreciably faster, but still not as fast as the fast code.
------
Slow baseline
```
python translate.py -model /home/dylan/Downloads/averaged-10-epoch.pt -src /home/dylan/Downloads/test_short.en -tgt /home/dylan/Downloads/test_short.de -verbose -output pred.txt -gpu 0 -report_time
```
```
PRED AVG SCORE: -0.4390, PRED PPL: 1.5512
GOLD AVG SCORE: -11.2287, GOLD PPL: 75260.5316
Total translation time (s): 40.024521
Average translation time (s): 0.080049
Tokens per second: 301.690056
```
Slow summary cov
```
python translate.py -model /home/dylan/Downloads/averaged-10-epoch.pt …
```

Implement coverage penalty in fast beam search

---

onmt/models/model_saver.py

Initial PR #1273 saved current model parameters instead of moving average due to a mishap in fixing conflicts.

Fix save moving average

---

docs/source/Summarization.md

There is an unused argument in an example that seems to have been refactored out.

Remove unused command line argument in documentation.

---

onmt/model_builder.py
onmt/tests/test_beam.py
onmt/tests/test_beam_search.py
onmt/translate/beam_search.py
onmt/translate/decode_strategy.py
onmt/translate/random_sampling.py
onmt/translate/translator.py

I've made ``.view`` calls more literate. By that I mean avoiding ``-1``'s and avoiding referencing the original tensor for dimensions in favor of using hopefully well-named variables. I've tried to make some of the instance attribute uses more readable, too. IMO when dealing with stateful instance attribute tensors, using a buffer/``out`` approach is more readable. So that's what I've done. I'm seeing the same scores, speed (non-significant difference, anyways), and memory usage.
Also,  #1277  broke ``return_attention`` when not using a coverage penalty. This fixes it, and unit tests it.

Better buffering, readability in beam_search; random sampling class

---

onmt/tests/test_random_sampling.py
onmt/translate/decode_strategy.py
onmt/translate/random_sampling.py
onmt/translate/translator.py

This fixes #1284 . Now the random sampling scores are the score of EOS. The finished batches are dropped, which should eventually make it easier to get to one translate loop since the beam search does that.

Random sampling scores

---

onmt/trainer.py

We noticed that fp16 moving average computation may underflow for some values of `-average_decay` (e.g. 1e10-4), and lead to diverging results, so we shall make it in `.float()` in either fp16 or fp32 training mode.

Compute and store moving average in fp32

---

onmt/decoders/ensemble.py
onmt/encoders/audio_encoder.py
onmt/model_builder.py
onmt/tests/test_models.py
onmt/tests/test_translation_server.py
onmt/train_single.py
onmt/translate/translation_server.py
onmt/translate/translator.py
onmt/utils/parse.py
preprocess.py
train.py
translate.py

Working towards addressing #1231. This moves validating opts and getting default ("dummy") opts into a new ``ArgumentParser`` class. By default, that class uses the desired formatters and adds the md help.
I do validation and updating close to the entry point so the rest of the code can assume opts are clean. I choose to do validation in ``main()``'s instead of ``if __name__``'s so that you could e.g. test that main fails if passed bad args. (I didn't add those tests. Just saying they could be useful.)
In updating test_models.py to use the new parser, I ran across a few things with the audio encoder test:
1. In test_models.py, ``opt.layers`` was never forwarded to ``opt.enc_layers``/``opt.dec_layers`` so the test where ``opt.enc_layers`` = 10 was running but the number of layers was still …

Revamp args

---

onmt/inputters/audio_dataset.py
onmt/inputters/dataset_base.py
onmt/inputters/image_dataset.py
onmt/inputters/inputter.py
onmt/inputters/text_dataset.py
onmt/model_builder.py
onmt/tests/test_models.py
onmt/train_single.py
onmt/trainer.py
onmt/translate/translation.py
onmt/translate/translator.py
tools/embeddings_to_torch.py
tools/extract_embeddings.py

This reduces the ``fields`` object to ``dict[str, Field]`` in all cases.
On #1292 it came up that ``fields`` is sometimes ``dict[str, list[tuple[str, Field]]]`` and sometimes ``[list[tuple[str, Field]]``. On the other hand, torchtext is (usually) using ``dict[str, Field]``.
I tested that you can:
Preprocess on master, train on PR.
Preprocess and train on master, translate on PR.
Preprocess and train on master, train from checkpoint on PR.
And pull request script checks against legacy formats.
So I think this is completely backwards compatible.

Simplify fields structure

---

onmt/model_builder.py
onmt/opts.py

On some hardware (GTX 1080/1080ti) FP16 is way slower than FP32.
this option allows to force FP32 decoding even if the model is FP16.

Allow forcing FP32 at inference of FP16 models

---

.travis.yml

The Travis shallow Git clone seems to cause issues with doctr:
```text
fatal: missing blob object '271af2ebbb5de8b1cb69c0b7e177bcc4ab2e34dc'
error: github.com:OpenNMT/OpenNMT-py.git did not send all necessary objects
```
Making a deep clone appears to fix this issue.

Fix doctr deploy

---

onmt/utils/parse.py

#1287 broke bidirectional encoding. This fixes it.

Fix bidirectional encoding

---

.travis.yml
requirements.opt.txt

This adds Flask as an optional dependency.
#1311 broke Github Pages. There was an error saying flask wasn't available. That would make it impossible to import server.py, which is now part of the docs. There's no tests on server.py directly so it makes sense that Travis didn't break. Not 100% sure this will fix it, but either way flask is an optional dependency so it should probably be listed here.

Add flask dependency

---

translate.py

`translate.py` would ignore all sentences after processing `shard_size*shard_size` sentences in `src`, if no `tgt` file was provided. This commit fixes this issue (#1317).
I've run all the tests as well, but none of them seem to actually target `translate.py`. I tested it manually using the following parameters on a ~1000 line source file:
```bash
python  translate.py --model model_step_10000.pt --src 1000-line-test.txt --batch_size 1 --shard_size 1 --output pred1.txt
python  translate.py --model model_step_10000.pt --src 1000-line-test.txt --batch_size 1 --output pred2.txt
python  translate.py --model model_step_10000.pt --src 1000-line-test.txt --output pred3.txt
python  translate.py --model model_step_10000.pt --src 1000-line-test.txt --batch_size 1 --shard_size 10 --output pred4.txt …
```

Fix translate.py bug (OpenNMT/OpenNMT-py#1317)

---

onmt/opts.py

Instructions on how to use `-src_vocab`.

Using -src_vocab to pass vocab.pt files.

---

onmt/inputters/inputter.py
onmt/opts.py
onmt/train_single.py
onmt/trainer.py
onmt/utils/optimizers.py
onmt/utils/parse.py

This PR introduces 2 things:
1) noam with decay (decay_method="noamwd")
When training on a lot of GPUs, the number of steps may be reduced (eg 50k) and you may want to decay faster the classic noam curve to a lower value.
2) accum gradient scheduler
When training on several GPUs, if you want a good performance you need a very high value of accum_count (eg 24 or more) but if you start training with such a huge batch size, it decreases the performance.
accum_count can now take a list of values, eg '4 8 16' which corresponds to a list of steps at which accum_count changes '10000 20000 30000'
Enjoy.

advanced noam with decay and accum scheduler

---

onmt/opts.py
onmt/translate/translation.py
onmt/translate/translator.py

If `phrase_table` is provided (with replace_unk), it will look up the identified source token and give the corresponding target token. If it is not provided (or the identified source token does not exist in the table), then it will copy the source token. Tested with both _translate.py_ and _server.py_ (with conf.json).
The default behaviour of the `-replace_unk` option is substituting `<unk>` (for an unknown word) with the source word that has the highest attention weight. Adding the option `-phrase_table` as well, it will look up in the phrase table file for a possible translation instead. If a valid replacement is not found, only then the source token will be copied.
The phrase table is a file with one translation per line in the format:
`source|||target`
Where source and target are …

Add phrase_table translation argument

---

README.md
docs/source/FAQ.md
tools/embeddings_to_torch.py

Fixes #1371
embeddings_to_torch.py is changed to only load vectors which are in the vocab into memory. When the vocab is small relative to the pretrained file, this significantly speeds up loading and makes it possible to preprocess large pretrained embedding files on machines with limited memory.

More efficient embeddings_to_torch.py

---

onmt/translate/translator.py

This PR modifies the Translator class to write the attention output (attn_debug=True) to the logger, instead of stdout, if the Translator object has a logger. Currently, the attention output is always written to stdout.

Write attention debug output to logger

---

onmt/opts.py
onmt/trainer.py
onmt/utils/__init__.py
onmt/utils/earlystopping.py

A very requested feature for training regularisation to avoid overfitting. Issue #1382 is an example of requesting this simple feature. 
This pull request uses the previous codebase for inspiration.
- Added option to opts.py regarding the number of validation steps without improving (tolerance);
- Added earlystopping callable to trainer.py (only for gpu rank==0);
- Added earlystopping logic: after validation deciding whether or not to stop training; added `onmt/utils/earlystopping.py` with all the logic. Design was made thinking about future metrics, should be fairly easy to add ROUGE or BLEU in the future. 
1. Add new scorer that extracts the metric from stats (TODO, add other metrics to stats during validation);
2. Register new scorer in `SCORER_BUILDER`.
- `... --early_stopping 4 …

Added earlystopping mechanism

---

onmt/utils/parse.py

This PR modifies the preprocessing code to check that src_vocab and tgt_vocab exist, if they are specified as parameters.
This prevents the problem where a user specifies vocab files that do not exist, and waits for the preprocessing script to reach the vocab generation step only to have the program crash.

Check vocabulary files exist at start of preprocessing

---

onmt/encoders/mean_encoder.py

Hi @pltrdy 
As we talked about, small patch in MeanEncoder that avoids including the padding when computing the mean.
Let me known if there's anything missing

Avoid padding indices in MeanEncoder

---

onmt/utils/parse.py

This PR modifies validate_train_opts() class method to check gpu_ranks option, to ensure saving a model against #1322, even though FAQ document covered this problem.
Assuming locally-distributed environment, list some possible cases:
(1) -world_size 1 and -gpu_ranks 1 --> raise assertion
(2) -world_size 2 and -gpu_ranks 1 3 2 0 --> raise assertion, truncate gpu_ranks array with world_size(=[1, 3])
(3) -world_size 4 and -gpu_ranks 2 3 --> safe, worker node
(4) -world_size 4 and -gpu_ranks 0 1 --> safe, master node
(5) -world_size 1(as default) without assigning gpu_ranks parameter explicitly --> safe, train.py will call single_main() methods, in case of 1 GPU only.
additionally, it modifies some AssertionError messages for indentation and print messages neatly.

Check -gpu_ranks option to ensure saving a model

---

onmt/inputters/inputter.py

@flauted this should fix the issue mentioned in #1413 
For reference: it was introduced [here](https://github.com/OpenNMT/OpenNMT-py/pull/1216/files#diff-55eec480db97bda4ea4ea8fc498bfad6L284). This, in combination with some -src_words_min_frequency or tgt_words_min_frequency option may lead to removing some of the last tokens of the vocab.

Fix unwanted behaviour when loading vocab from text file with words frequency option

---

onmt/train_single.py

#1413 made it systematic to use MultipleDatasetIterator, even when not needed.
This may cause issues when wanting to use `-single_pass` on a single dataset, or lead to loading some shards too many times (linked to the pool mechanism, at the `MultipleDatasetIterator`, pooling from several 'sub-iterators', instead of `DatasetLazyIter`).
Should fix #1435 .

[fix] Make MultipleDatasetIterator only if necessary

---

README.md

Just a note to ones who try it to install the pyTorch dependencies without enough cache memory

Update README.md because MemoryError

---

onmt/inputters/inputter.py

Having some data_ids with a common root meant that some shards were loaded by several iterators.

[fix] Fix issue when several data_ids have same root

---

onmt/inputters/dataset_base.py
onmt/inputters/inputter.py
onmt/modules/copy_generator.py
onmt/opts.py
onmt/train_single.py
onmt/trainer.py
preprocess.py
train.py

Goal: load the dataset only once in RAM (instead of n_gpu times) which enables much bigger datasets or less sharding.
The idea is to have a producer that reads data (i.e. shards) and sends batch to consumers (i.e. process that actually trains the model).
It's *quite* working now, but we're still investigating not trivial cases with @francoishernandez  (including Multiple dataset that show weird behavior)

Using Producer-Consumer for batches

---

README.md

Change the wording to avoid confusion. Mixed precision ensures both higher arithmetic throughput and numerical stability, not exactly synonymous to pure half-precision/FP16 training. Also add mentioning of tensor cores since older generation GPUs without tensor cores don't support true mixed precision training.

Clarify mixed precision training support

---

onmt/model_builder.py
onmt/opts.py
onmt/trainer.py
onmt/utils/optimizers.py
onmt/utils/parse.py

This PR updates the current mixed precision codepath with the new apex amp API according to the [guidelines](https://nvidia.github.io/apex/amp.html#transition-guide-for-old-api-users).
Default is `opt_level` "O2" which seems to correspond to what we were doing before. This can be changed by passing the `-apex_opt_level` option.

New apex amp API

---

onmt/translate/translation.py

When using `translate.py` with `replace_unk`,  the argmax of the attention can potentially be on the padding instead of a real source token.
The code currently uses: `_, max_index = attn[i].max(0)` and uses this value to retrieve the token from the source sequence: `src_raw[max_index.item()]`.
However, `max_index.item()` can potentially be greater than the length of `src_raw`, which results in: `IndexError: list index out of range`.
This fix takes the argmax of the attention only among the actual source tokens. 
(by the way, this never happened to me in the past, although I am using the exact same settings for a long time now)

Fix a potential IndexError when translating with replace_unk

---

onmt/modules/multi_headed_attn.py

`mask` refers to positions which need to have zero-attention. This is also suggested by line 200 in same file `scores.masked_fill(mask, -1e18)`

Minor change in MultiHeadedAttention  documentation

---

onmt/modules/copy_generator.py
onmt/opts.py
onmt/utils/loss.py

Implement coverage loss, that is related to `--lambda_coverage` flag, which was present but unused.
Using `--lambda_coverage = 0` (default) ignores the coverage loss. Any value of `--lambda_coverage != 0` requires `--coverage_attn`.

Implementing coverage loss of abisee (2017)

---

onmt/inputters/inputter.py

Should fix #1484 .
This should not interrupt training, but warn the user that some example is ignored.

Ignore example if over allowed tokens batch, add warning

---

onmt/translate/translation_server.py

Allow implicit `batch_size` in `translation_server` when setting "batch_size" option to 0 in config.
This allows to consider the size of the batch sent in the request as the batch_size for inference.

Allow implicit batch_size in translation_server

---

onmt/utils/misc.py

`sequence_mask` could be built on wrong device if `torch.cuda.current_device()` was different than `lengths.device` (which is the device where stuff should happen).

[fix] ensure building sequence mask on same device as lengths

---

onmt/train_single.py

Fixes some issue raised in #1498 .
This code path might need some refactoring at some point though.

[fix] Make dataset iterator consistent train/train_single

---

onmt/translate/process_zh.py
onmt/translate/translation_server.py

Add preprocess and postprocess option in REST server. As its usually needed in some cases, like normalize punctuation. Particularly useful for Chinese language, as there are different standard for Chinese. To use these two option, you need to pass a list of python function in a json configure file as the process pipeline. The function receive the sentence as argument and return processed sentence.
Ex:
"preprocess":[
"onmt.translate.process_zh.zh_simplify",
"onmt.translate.process_zh.zh_segmentator"
],
"postprocess":[
"onmt.translate.process_zh.punctuation_en2zh",
"onmt.translate.process_zh.zh_traditional_standard"
]

Use functions as preprocess / postprocess in REST server

---

preprocess.py

There were some implicit checks on `src_vocab` and `tgt_vocab` in preprocessing.
This was creating some unwanted behavior when loading an existing vocab as a text file.

[fix] remove implicit check in preprocess

---

onmt/decoders/transformer.py
onmt/modules/global_attention.py
onmt/translate/beam_search.py

This PR tracks the changes needed to make the codebase compatible with the recent [pytorch 1.2 release](https://github.com/pytorch/pytorch/releases/tag/v1.2.0).
The only issues encountered for now are consequences of the introduction of `torch.BoolTensor`. Some others may appear down the line.
Should fix #1524 #1525.

Pytorch 1.2 compatibility for mask manipulation

---

tools/create_vocabulary.py

This PR modifies tools/create_vocabulary.py, to help beginners to assign -side arguments properly when using -file_type 'field'. and additionaly, able to run without install OpenNMT-py.

add simple -side argument check and help messages for -file_type 'field'

---

onmt/opts.py
onmt/utils/report_manager.py
requirements.opt.txt

Switch to official TensorBoard support by Pytorch since v1.1.0.
No need to install tensorboardX anymore, use torch.utils.tensorboard instead.
To visualize the training with TensorBoard GUI, we need the package TensorBoard >= 1.14.

Switch tensorboardX to official TensorBoard

---

onmt/utils/loss.py

Sum on all dimensions in order to get a scalar result instead of a tensor.
* supposed to fix https://github.com/OpenNMT/OpenNMT-py/issues/1528
(this PR is not much tested at the moment)

Fixing coverage loss computation

---

.travis.yml
README.md

Python2 will go out of support by year end, we remove it from Travis tests.
NB: Distributed (multigpu requires Python 3 anyway)
Some new PR may not support Python2.
Switch to Pytorch 1.2

Remove Python2 Travis / switch to pytorch 1.2

---

onmt/model_builder.py
onmt/models/model_saver.py
onmt/opts.py
onmt/trainer.py
onmt/utils/optimizers.py

Here is the issue:
For FP16 training, we use Nvidia/apex.
They changed the API to something called AMP and we adapted to this new API on June 13.
However, a few things are broken in this new API when it comes to handle FusedAdam.
On Aug 8 they included FusedAdam in the AMP new API but I realized that:
O2 level does not work at all for both Adam and FuseAdam (O2 was our Default level).
see https://github.com/NVIDIA/apex/issues/475
O1 level works fine for Adam but does work (unstable) with FusedAdam.
This PR will:
1) Default to O1 with Adam/AMP (FP16 training only)
2) Use the Legacy FusedAdam code that we have included in optimizer.py
This solution should be temporary since Nvidia works on including AMP directly in Pytorch.
As of this PR, Accuracy/PPL are ok for Adam FP32, Adam FP16, …

FP16 training fix

---

onmt/opts.py
preprocess.py

This PR is following #1413 .
_This was simplified from the initial proposition._
We build a single iterator `shard_iterator` that yields everything required to build a shard, and call a `multiprocessing.Pool.imap` over it to process shards and build the vocab counters in parallel (`opt.num_threads`).
The shard processing is done in `process_one_shard`.
Depending on the configuration, we can achieve up to 10x speed up.
Note: it is not advised to use this option for image or audio tasks, as feature computation is already mostly multi-threaded (and close to maxing out CPU resources).
Note 2: this should also fix an issue when preprocessing audio (some counter of src features was being built when building vocab). #1576

Use multiprocessing to speed up preprocessing

---

setup.py

We set the project `README.md` as the long description, which is what PyPi is using for the package page (see example: https://test.pypi.org/project/OpenNMT-py/1.0.0rc10/ ) 
---
NOTE: I had to bump the version (1.0.0rc10) for PyPi test upload for test reasons (even on test versions are unique...)

Add long description to `setup.py` (for pypi)

---

Dockerfile

I suggest removing the Dockerfile.
The OpenNMT-py installation procedure is no longer valid and the file does not provide much value.

Remove Dockerfile

---

setup.py

The package is not built for other systems.

Only require pyonmttok on Linux systems

---

tools/embeddings_to_torch.py

Fixed a bug when correctly loaded dec embedding will report alarming number of missing vectors.

fixed stats printout

---

docs/source/FAQ.md

This separates the "multi-gpu" question in the FAQ, adds a note about producer/consumer setup and explains why we can't have GPUs in exclusive mode.

[docs] Add note about producer/consumer in FAQ

---

onmt/translate/translator.py

In copy generator, `copy_prob` is `[batch, tl, cvocab]` right after `bmm`, then become `[tl, batch, cvocab]` after transposition, and get "flattened"(`tlen` first) at line 131, `[tl*batch, cvocab]`.
In [translator line 601](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translator.py#L601), we try to view it as `batch, tl, scores.size(-1)`(batch first), which is inconsistent with previous flattening. 
I reproduced the error by looking at values right after `bmm` (before transpose), and right after line 601. Because `scores` has same dimensions at both points, values should be the same, but it's not.
--- 
fixes: https://github.com/OpenNMT/OpenNMT-py/issues/1607

Fix _decode_and_generate for gold scoring w/ copy

---

onmt/utils/report_manager.py

Not sure what `progress_step` was meant for (even if I wrote it...), in practice it's less consistent with other tensorboard reports (which are based on step). Using `step` makes more sense.

remove `progress_step` from `report_manager`

---

onmt/models/model_saver.py
onmt/trainer.py

Deepcopy isn't mandatory here, we just need to keep the original parameters somewhere, and put it back after validation.
This is probably more efficient in term of speed and memory.
---
**EDIT:** Current training ran validation and saved checkpoint without issues. I'll check if performance are affected. 
Cannot really compare speed/memory impact as I never trained using older version.

do not deepcopy during validation w/ moving_average

---

onmt/bin/server.py
onmt/tests/test_translation_server.py
onmt/translate/translation_server.py

Solve issus  #1614. Support server output n_best translation.
With this PR, server will output translation as:
```json
[
[
{
"n_best": 2, 
"pred_score": -0.15397775173187256, 
"src": "text to translate 1.", 
"tgt": "translation 1 - 1_best."
}, 
{
"n_best": 2, 
"pred_score": -0.2884165942668915, 
"src": "text to translate 2.", 
"tgt": "translation 2 - 1_best."
}
],
[
{
"n_best": 2, 
"pred_score": -0.5973197817802429, 
"src": "text to translate 1.", 
"tgt": "translation 1 - 2_best."
}, 
{
"n_best": 2, 
"pred_score": -0.5908429622650146, 
"src": "text to translate 2.", 
"tgt": "translation 2 - 2_best."
}
]
]
```

support server for nbest translation

---

onmt/translate/beam_search.py

This PR is intended to fix beam search with vanilla coverage penalty (`-coverage_penalty` set other than 'none' while not set `-stepwise_penalty`) in the case of FP16 model (and not set `-fp32`).
Without this PR, the this.topk_scores is in float32 dtype, while cov_penalty calculated based on attention is float16 dtype (for transformer), this will raise `RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Half`.

fix vanilla coverage penalty with FP16 model

---

onmt/bin/train.py

This fixes a case when training with multiple datasets on multiple GPUs, the iterator does not use the proper seed.
`MultipleDatasetIterator` initialises its `random_shuffler` in the main process, whereas in the case of a single dataset, `DatasetLazyIterator` initialises it on the first iteration, which happens in the `batch_producer` process, where the torch seed is properly initialized.

[fix] Add missing seed init

---

onmt/bin/average_models.py
setup.py
tools/average_models.py

This PR just moves the averaging of models logic from `tools` to `onmt.bin`, and create the corresponding entry point to simplify its use.

Move average_models to onmt.bin, create entry point

---

onmt/opts.py
onmt/translate/translator.py

#1429 #1530 #1618
We propose to remove, at least for now, the `-report_bleu` and `report_rouge` options for `translate`. It is not working properly since #1192 and #1639 would not fix this properly.
If one wants to get BLEU or ROUGE scores, some fairly simple tools are widely available.

Remove -report_bleu and -report_rouge options from translate

---

onmt/translate/translator.py

Now calculate `ppl` with `numpy` instead of `math` which converts overflow to `inf` and prints a warning (which make sense imo).
Fix #1655

Fix overflow error on translation perplexity

---

onmt/decoders/ensemble.py

This PR fixes the use of joint alignment models in ensemble decoding by:
* Add the forgotten additional argument pass for EnsembleDecoder.

fix the use of joint alignment model in emsemble

---

docs/source/refs.bib
onmt/decoders/transformer.py
onmt/opts.py

This PR:
* Improve the documentation in Transformer decoder
* Clarify IO tensor shape under train and inference(stepwise decoding)
* Complete argument description.
* Default the alignment_heads to 0 rather than None

More documentation for transformer decoder, default alignment_heads

---

onmt/model_builder.py

The `share_decoder_embeddings` option is not implemented (the flag is ignored silently) when using the `CopyGenerator`.

Use share_decoder_embeddings w/ copy generator

---

.travis.yml
onmt/translate/translation_server.py
requirements.opt.txt
setup.py

A memory leak was flagged when rebuilding `pyonmttok.Tokenizer` objects (https://github.com/OpenNMT/Tokenizer/issues/130).
We move the tokenizer initialization in the `ServerModel` constructor, as well as the eventual preprocess/postprocess. Everything is built once when 'preloading' the models.
+ Update requirements to pytorch 1.4 (1.3.1 was breaking travis - https://github.com/pytorch/vision/issues/1675).
+ Remove Pillow pin to <7 (torchaudio 0.5 released along with pytorch 1.4)

move tok/preproc/postproc init to ServerModel init

---

onmt/models/model_saver.py

Without this check, the training would stop if some checkpoints were removed manually before they are removed based on the `-keep_checkpoint` opt.

[fix] Check if checkpoint exists before removing

---

onmt/bin/release_model.py
setup.py
tools/release_model.py

I propose this change to facilitate the conversion of OpenNMT-py models to the CTranslate2 format. This also moves the release script inside the Python package as it seems generally useful.
Note: I did not add `ctranslate2` as a dependency as it requires a recent version of `pip` (>= 19). It could be added in the future when other packages have the same requirement.

Extend release script with CTranslate2 conversion

---

onmt/decoders/transformer.py

I've been inverstigating about differences between [Ziegler's fork](https://github.com/harvardnlp/encoder-agnostic-adaptation) and ONMT-py.
Turns out the attention dropout isn't used the same way i.e. using attn_dropout for the self attention (which make sense) and not for the context attention (less clear to me if it should be), see https://github.com/harvardnlp/encoder-agnostic-adaptation/blob/master/onmt/decoders/transformer.py#L274 .
I'm currently training summarization models with this variant, since I observed a performance gap between our and Ziegler's implementation.

Use attention dropout for self attention, not context

---

onmt/inputters/inputter.py

I found it more practical to log the glob since `opt.data` only contain the prefix, i.e. without corpus type / corpus ids

Make "Training data not found" a bit more explicit

---

onmt/opts.py

Not sure why the queue size is *that* big. It seems pretty useless to me (I may miss something) and actually lowering it helped it avoid out of memory during training without loss of performance.
For the context, I regularly face some OOM, only right after (or before) validation.
I don't really understand why, but since I considered this big queue to be a waste of memory I reduced it and eventually fix the issue (it may just be random, but anyway queue size 400 does not really make sense to me).

lower default batch producer queue size

---

docs/source/FAQ.md

Right now, at
https://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-pretrained-embeddings-e-g-glove,
all numbers in the steps show up as "1". This commit should fix this.

FAQ.md: Fix numbering

---

onmt/translate/translation.py

In this PR, We default the use of alignment to do `--replace_unk`, This is only valid for Transformer if we set the `--report_align`.
This feature will benefit a lot for those Transformer trained with guided alignments. And should also help (but less accurate compare to guided alignment) for any Transformer model as we'll default to average the second last layer's attention rather than the top head of the last decoder layer if we set `--report_align` during translate.

default replace_unk to alignment if exist for transformer

---

onmt/bin/release_model.py

1. patch CT2 conversion code to handle cases where `opt.layers` is not set (but `opt.enc_layers` and `opt.dec_layers` are).
2. handle `quantization` option to apply proper quantization to CT2 conversion

Update ctranslate2 options in release_model

---

onmt/bin/server.py
onmt/tests/test_translation_server.py
onmt/translate/process_zh.py
onmt/translate/translation_server.py

This PR introduces a change in the way segments are handled in the REST server.
Originally being only strings, segments will now be handled as a dict, to allow more flexibility for custom preprocessing/postprocessing functions.

Use return_dict in REST server for more flexibility

---

onmt/translate/translation_server.py

#1745 broke the handling of `None` alignments for empty segments.

[fix] Handle batches with empty segments in server

---

onmt/inputters/inputter.py

Sort shard based on their number instead of string sort i.e.  `0 -> 1 -> 10 -> 100 -> 101 ...`

fix dataset shard order

---

onmt/translate/translation_server.py
onmt/utils/alignment.py

This PR fixes the error when extract alignment from a prediction with no valid tokens.
This rarely happens only when src has only a few special tokens while its prediction early stops with no valid token other than `<bos>`, `<eos>`, and `<pad>`.

Fix alignment error when prediction have no valid token

---

onmt/bin/server.py
onmt/translate/translation_server.py

This PR adds the support of CTranslate2 models via the `ctranslate2.Translator` python class.
For now, if a model has a `"ct2_model`" defined, then it will be used, else it will fall back to the pytorch one.
We could probably add a `"model_format"` parameter if ever there were more formats to come in the future.
Note: when preloading a model at startup, it will perform a dummy translation to initialize everything. Without this, preloading is fairly useless as there are some time consuming initialization steps performed on the first inference.

Add support of CTranslate2 models in REST server

---

onmt/bin/release_model.py

This is supported since version 1.7.

Enable CTranslate2 release of models with different enc/dec layers

---

onmt/translate/process_zh.py
onmt/translate/translation_server.py

We just pass the `self` `ServerModel` object to any preprocessing or postprocessing function.
This allows more flexibility for potential custom functions.

A bit more flexibility to REST server pre/postprocess functions

---

onmt/inputters/inputter.py

1. Useless to have such datasets be initialised.
2. May cause some issues in this hack where we take the `.dataset` of the first item in the list:
https://github.com/OpenNMT/OpenNMT-py/blob/c20dbeac02688918607637f5f30ec73c0f17d817/onmt/inputters/inputter.py#L760-L762
Thanks @Zenglinxiao for noticing!

[fix] Filter out datasets with weight <=0 in MultipleDatasetIterator

---

onmt/translate/translator.py

Fix IndexError appears for the guided alignment model in the condition of passing -tgt with -replace_token option on as indicated in #1787 .
Previously, before we enable the option `-replace_unk` for the guided alignment model, we intend to get the alignment between `-src` and `-tgt` if golden tgt is passed as a way to debug and test the performance of alignment. This will not raise conflicts the time when we haven't enable the alignment for unknown token replacement. But becoming an issue as we now enable the alignment matrix to be used to align the correct src token if an unknown token is detected in the prediction. This implicit handling makes the replacement inconsistent as the alignment matrix used in the replace_unk is actually the alignment between src and golden tgt rather than …

fix indexerror for guided alignment model 

---

docs/requirements.txt
docs/source/index.rst

This PR was originally made to try and understand why some pages are missing from the docs.
It seems sphinx 3.0.3 is at fault here. Staying with 2.4.4 for now.

[docs] Fix docs

---

setup.py

The version of the dependency tqdm was frozen due to some problems connected with travis, see #1278 
I verified that the current version of tqdm works with travis, see https://travis-ci.org/github/akreuzer/OpenNMT-py/builds/692003183
Therefore, one should unfreeze the version. This will help to avoid some decency conflicts this may have caused.

Removed version freeze from tqdm

---

onmt/inputters/inputter.py
onmt/opts.py

For now when `-model_dtype` is `fp16`, `batch_size_multiple` is automatically set to 8 in `onmt.inputters.inputter` (to optimize usage of tensor cores). Though, in some cases it may cause more harm than good and it can be useful to disable it.
Hence, this PR introduces the `-batch_size_multiple` flag to override with a specific value.

Add flag to override batch_size_multiple

---

onmt/opts.py
onmt/translate/beam_search.py
onmt/translate/decode_strategy.py
onmt/translate/greedy_search.py
onmt/translate/translator.py
onmt/utils/parse.py

In this PR, the prefix decoding feature is added, enable us to generate the prediction begin with provided lines as prefix.
To use this feature, we need to pass the prefix file as `-tgt`, and specify `-tgt_prefix` to enable this feature.

add target_prefix decoding feature

---

onmt/translate/translation_server.py

This allows further extendability for cusom preprocessing functions.
(Also removes the unused `sslength` variable.)
cc @Zenglinxiao

Pass whole segment dict to preprocess function instead of just src

---

onmt/bin/server.py
onmt/translate/translation_server.py
onmt/translate/translator.py
onmt/utils/alignment.py
onmt/utils/parse.py

In this PR:
- We add the support of the different types of tokenizer in the REST server: as previously, a tokenizer specified with src side opt, may encounter problem when decoding tgt side prediction; e.g. the model is trained with `joiner` in src and `spacer` in tgt and vice versa.
- We add the support to feed also reference alongside the source text  to the translator;
- Some fixes related to the above topic.

Allow different tokenization for source and target in REST server configuration

---

onmt/translate/translation_server.py
requirements.opt.txt

In this PR, we add a `custom_opt` in `ServerModel` so that external function like `preprocess`/`postprocess` can be configurable.
Note: we also pin `numba==0.43.0` and `llvmlite==0.32.1` in `requirements.opt.txt` to allow travis to run (https://github.com/librosa/librosa/issues/1160 // https://github.com/deezer/spleeter/issues/419)

add custom_opt in REST server

---

onmt/translate/translation_server.py

Bug was introduced in #1810 
When looping on `zip(seg, ref)`, `ref` may be `[None]`, so we need to make sure to loop on all the segs.
Hence, we replace `zip` by `zip_longest`.

[fix] Fix some broken loop in rest server

---

onmt/inputters/inputter.py

Warning was quite misleading. No example is ignored, the only issue is that final batch size may exceed the set value.

Better warning for batch_size_multiple overflow

---

onmt/bin/preprocess.py

When using --data_type vec, the logic in `process_one_shard` in onmt/bin/preprocess.py adds each feature vector into the source vocabulary. Besides being unnecessary (I think it's not finally saved in the vocabulary file), this causes the preprocessing to fail if there are enough vectors because the torch.multiprocessing worker assigns each of them a shared memory segment and a file handle, which are fairly limited resources, when sending the vocabulary to a different thread:
```
$ onmt_preprocess --data_type vec --train_src nt/vec_files.txt --train_tgt nt/tokens.txt --valid_src ot/vec_files.txt --valid_tgt ot/tokens.txt --save_data data --shard_size 10240
[2020-07-21 01:45:40,163 INFO] Extracting features...
[2020-07-21 01:45:40,163 INFO]  * number of source features: 0.
[2020-07-21 …
```

Fix --data_type vec to not build vocabulary with tensors as keys.

---

onmt/decoders/transformer.py

looks like a copy paste error. The transformer encoder doesn't fall back to dropout if attention_dropout is not a list.

fix attention_dropout in transformer decoder

---

.travis.yml
onmt/inputters/audio_dataset.py
onmt/inputters/vec_dataset.py
onmt/modules/source_noise.py
onmt/tests/test_audio_dataset.py
onmt/tests/test_beam_search.py
onmt/tests/test_copy_generator.py
onmt/translate/beam_search.py
onmt/translate/greedy_search.py
requirements.opt.txt

This PR fixes some BC break changes and deprecations made by torch1.6:
* ` // ` replace `torch.div` for float division;
* specify dtype for `torch.full` if fill value is int/bool;
* missing argument for `torch.nonzero(as_tuple=bool)`.
Fix #1838

fix relate to torch1.6

---

onmt/bin/preprocess.py
onmt/decoders/transformer.py
onmt/tests/test_beam_search.py
onmt/translate/decode_strategy.py

Use `deepcopy` instead of `dict` to protect values from in-place modifications.
Not using it result in some tokens being forbidden for no good reason.

Fix block_ngram_repeat w/ deepcopy

---

onmt/trainer.py
onmt/utils/report_manager.py
onmt/utils/statistics.py

If early stopping is used, a separate scalar will be added to the tensorboard logger. This will show the patience, particularly the current tolerance that is left at each training step.
Not sure if this should be logged during training or evaluation or both. Currently it is logged in both. If this needs to change; `self.maybe_log_tensorboard` inside `ReportMgr._report_step` should take `None` as patience value.
closes https://github.com/OpenNMT/OpenNMT-py/issues/1834

Add patience to tensorboard logging

---

docs/source/FAQ.md
onmt/model_builder.py
onmt/modules/embeddings.py
onmt/opts.py
onmt/tests/test_embeddings.py
onmt/utils/parse.py
tools/extract_embeddings.py

Hi, according to #1866 I changed the help string for the `fix_word_vecs_*` to be clearer about what it does.
I wonder whether it is necessary to change the variable names using this option as well ?
I think just changing the help is enough string will help user understand what this does.
The 3 files using this option:
- [onmt/model_builder.py](https://github.com/OpenNMT/OpenNMT-py/blob/2c63a535c8c85ba77eeac2e179cfa0e70d0a90fe/onmt/model_builder.py#L37)
- [onmt/modules/embeddings.py](https://github.com/OpenNMT/OpenNMT-py/blob/2c63a535c8c85ba77eeac2e179cfa0e70d0a90fe/onmt/modules/embeddings.py#L110)
- [onmt/tests/test_embeddings.py](https://github.com/OpenNMT/OpenNMT-py/blob/2c63a535c8c85ba77eeac2e179cfa0e70d0a90fe/onmt/tests/test_embeddings.py#L24)
This file explains what the option does …

Update help string for `fix_word_vecs_*`

---

onmt/bin/release_model.py

Model conversion to float16 is supported since CTranslate2 1.12.0.

Add float16 to CTranslate2 export types

---

onmt/inputters/fields.py
onmt/transforms/sampling.py

May be useful to have the full vocab object in some transforms (to have the `freqs` for instance).

Return full torchtext vocabs in get_vocabs instead of only itos

---

onmt/transforms/bart.py

Rotate ratio is set to .5 by default. Therefore, by using e.g. `transform=bart mask_ratio=0.3` the resulting bart noise will also use `rotate_ratio=0.5` which isn't expected by the user imo.

BART: disable rotate ratio by default

---

README.md

The project uses f-Strings which are not available in Python 3.5.

Update required Python version to 3.6

---

onmt/bin/build_vocab.py
onmt/inputters/corpus.py
onmt/inputters/dynamic_iterator.py
onmt/opts.py

@Zenglinxiao following our discussion:
- the `write_files_from_queues` process still slows down the process significantly (probably due to interprocess communication through Queues);
- to allow fast execution, I made the dump optional, through the `-dump_samples` flag.
Ohter flags introduced:
- `-num_threads`, to set the number of threads used for `onmt_build_vocab`;
- `-vocab_sample_queue_size`, to set the size of the queues used to send data to the sample writing process.
Note: I also moved the `DatasetAdapter` class to `onmt.inputters.corpus` to prevent some potential import conflicts.

Parallelize onmt_build_vocab

---

onmt/model_builder.py
onmt/modules/copy_generator.py

The Linear layer of the generator which intended to mapping hidden states to word vector space is the reverse operation of Embeddings, thus should not have the bias parameter. Adding bias will break the intention of `share_decoder_embeddings`.
This PR fixes this issue.

remove bias parameter from generator linear

---

onmt/transforms/bart.py
onmt/transforms/misc.py
onmt/transforms/sampling.py
onmt/transforms/tokenize.py
onmt/transforms/transform.py

Previously, we can't actually guarantee the reproducibility for sampling/tokenize transforms.
For tokenize related transforms, it was not possible for setting the seed for `sentencepiece` & `pyonmttok` until recently, see OpenNMT/Tokenizer#168 or google/sentencepiece#540. For sampling, as we've used `random` module in the transform, we can not depend on the already exist `set_random_seed` utils, as `random` not depend on RandomState as `numpy` or `torch`, see numpy/numpy#9650.
To adress these issues, we added `_set_seed` method in the `Transform` to ensure set the seed when initilize / load every transform instance.
This PR changes:
1. `_set_seed` method in the `Transform` base class for override in order to make the transform process reproducible;
2. add support for subword tokenize …

ensure reproducibility for data transforms

---

onmt/transforms/tokenize.py

keyword argument `vocabs` in warm_up() not match base class, will raise TypeError when run.

fix keyword arg error

---

onmt/transforms/bart.py
onmt/transforms/transform.py

Currently, vocabs added in `Transform.warm_up()` is not properly pickled/unpickled which will introduce Exception when using BART or SwitchOut transform in multi-gpu training. This PR fixes this issue by pickling a dict as state info.
This closes #1923.

fix missing vocabs in Transform.warm_up

---

onmt/model_builder.py
onmt/modules/copy_generator.py

Reverts OpenNMT/OpenNMT-py#1903
See discussions in #1903. We'll revert it for now. It doesn't change much to the model anyways.

Revert "remove bias parameter from generator linear"

---

docs/requirements.txt
docs/source/conf.py

`make html` was not working due to a silent update of sphinx
- freeze dependencies
- add recommonmark correctly https://recommonmark.readthedocs.io/en/latest/

fix building of documentation

---

setup.py

The module API will not change as long as it is in V1, so it is quite safe to relax the version requirement.
Also the latest version has wheels for macOS, so the platform check is updated accordingly.

Upgrade pyonmttok package and relax the version requirement

---

onmt/transforms/bart.py

So just using `-mask_length span-poisson` imply lambda=3.0, as in the paper.

BART: set `-poisson_lambda` default to 3.0

---

data/data_lm/gen-beam-sol.txt
data/data_lm/gen-sampling-sol.txt
onmt/bin/build_vocab.py
onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/modules/average_attn.py
onmt/modules/embeddings.py
onmt/modules/position_ffn.py
onmt/opts.py
onmt/tests/rebuild_test_models.sh
onmt/tests/test_beam_search.py

- fix transformer lm architecture to be in compliance with gpt2 original paper (removed one normalization layer, removed one residual addition)
- fix inference regarding step/cache usage (positional embedding when input is not a single word, keep mask if input is not a single word)
- factorize decoder.transformer.py
- rebuild model and fix tests
A difference remains in PositionwiseFeedForward: gpt2 in using GELU and we are using ReLU (option to chose the activation function added)
Also huggingface implementation has only one dropout in their corresponding PositionwiseFeedForward

Fix gpt2 architecture and inference

---

setup.py

This is to support installing OpenNMT-py alongside TensorFlow projects which may have higher TensorBoard version requirement.

Relax tensorboard version requirement to 2.x

---

setup.py

`tqdm` follows semantic versioning: https://github.com/tqdm/tqdm/blob/master/CONTRIBUTING.md#semantic-versioning

Relax tqdm version requirement to 4.x

---

setup.py

`configargparse` follows semantic versioning: https://github.com/bw2/ConfigArgParse#versioning

Relax configargparse version requirement to 1.x

---

.github/workflows/push.yml
.github/workflows/release.yml
setup.py

Numpy is already a dependency of PyTorch, which probably has a more specific Numpy version requirement than OpenNMT-py.

Remove explicit dependency to numpy

---

setup.py

Looks like the `six` dependency reappeared during a merge. It would have been easier if I sent all changes in one PR. Sorry!

Remove six dependency (bis)

---

data/data_lm/gen-sampling-beams-sol.txt
onmt/translate/decode_strategy.py

target_prefix has bos and eos tokens. EOS token must be removed from the count to have the correct min and max length

Fix target_prefix length

---

onmt/model_builder.py
onmt/utils/parse.py

This is a PR to fix some issues with checkpoint's vocabulary updating.
1. Fixed validation to accept `reset_optim` to be either "states" or "all"
2. Overrides checkpoint `update_vocab=False` on inference

Update checkpoint vocabulary (fix)

---

onmt/translate/beam_search.py

Currently, we may get the following warning when inference with beam_search under recent PyTorch.
```
...onmt/translate/beam_search.py:209: UserWarning: An output with one or more elements was resized since it had shape [255], which does not match the required output shape [51, 5].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /pytorch/aten/src/ATen/native/Resize.cpp:19.)
```
This behavior linked to the [proposal](https://github.com/pytorch/pytorch/issues/41027) in PyTorch. This PR fixes this warning.
Also, the buffers reuse in the topk pick is also fixed together with revision of related …

Fix beam warning and buffers reuse

---

examples/scripts/prepare_wmt_data.sh

It is probably changed false in a local environment and pushed to this repository. It should be "true" I guess.
You can check the related forum topic here: https://forum.opennmt.net/t/wmt14-translation-script/4347/2?u=chopinml

SentencePiece code block is in "False"

---

onmt/inputters/corpus.py
onmt/transforms/bart.py
onmt/transforms/sampling.py
onmt/transforms/transform.py

The transforms that require vocab could not be applied if we don't provide the required vocabulary. We should not provide them when build_vocab, but only in the training phase when the vocabulary is already available.
Currently, we check this in the transform.apply which may be misleading and not optimal.
In this PR, we do the check when building the transform object, those transform requires vocabulary will not be instantiated if we don't provide them vocab as in `build_vocab.py` and should raise an explicit error when we tried to.

Better handle transforms that require vocab

---

onmt/inputters/corpus.py

Currently, when dumping samples after applying transforms in the `onmt_build_vocab`, we may encounter a deadlock issue if the `filtertoolong` exist in the transform pipe.
The multiprocessing dumping using `num_threads` queue, each corresponds to one shard of original corpus and they are supposed to be equal size. This equal size assumption will be broken by the `filtertoolong` transform as there may have a different number of examples removed from that shard which will also break the ordering when writing.
To fix it, we need to pass a placeholder even that example has been filtered. Thus guaranteed the equal size assumption.

fix deadlock when dump samples with filter

---

onmt/bin/release_model.py
onmt/translate/translation_server.py

Conversion of OpenNMT-py models is now simpler. The options are checked inside the converter.

Update CTranslate2 usage for 2.0

---

examples/onmt.train.fp16.transformer.yaml

I trained a model config by `examples/onmt.train.fp16.transformer.yaml`. I convert trained model by command `onmt_release_model -m general_en_zh_step_90000.pt -o ct2_convert --format ctranslate2 -q int8`. The error raised.
```
Traceback (most recent call last):
File "/home/hanbing/miniconda3/bin/onmt_release_model", line 33, in <module>
sys.exit(load_entry_point('OpenNMT-py', 'console_scripts', 'onmt_release_model')())
File "/home/hanbing/projects/OpenNMT-py/onmt/bin/release_model.py", line 35, in main
quantization=opt.quantization)
File "/home/hanbing/miniconda3/lib/python3.7/site-packages/ctranslate2/converters/converter.py", line 45, in convert
model_spec = self._load()
File "/home/hanbing/miniconda3/lib/python3.7/site-packages/ctranslate2/converters/opennmt_py.py", line 63, in _load …
```

Set position_encoding to True in transformer example config.

---

setup.py

The package is now available on Linux, macOS, and Windows.

Remove environment markers for pyonmttok package

---

onmt/tests/pull_request_chk.sh
onmt/translate/translation_server.py

Config example:
```
{
"models_root": "/models",
"models": [
{
"id": 100,
"model": "ctranslate_model",
"ct2_model": "ctranslate_model",
"timeout": 600,
"on_timeout": "to_cpu",
"load": true,
"ct2_translate_batch_args":{
"max_batch_size":1,
"beam_size": 6,
"num_hypotheses":1,
"max_decoding_length": 6,
"min_decoding_length": 6
},
"ct2_translator_args": {
"device": "cuda",
"device_index": 0,
"intra_threads": 1,
"inter_threads": 1,
"compute_type": "default"
},
"opt": {
"gpu": 0,
"batch_size": 1,
"beam_size": 6,
"n_best": 1,
"min_length": 6,
"max_length": 6,
"length_penalty": "avg",
"random_sampling_topk": 0,
"random_sampling_topp": 0,
"random_sampling_temp": 1,
"ban_unk_token": true
},
"tokenizer": {
"type": "pyonmttok",
"mode": "aggressive",
"params": {
"joiner_annotate": true, …
```

Add two dictionnaries to accept unconstrained CT2 configurations

---

onmt/translate/translation_server.py

This PR modifies the server to allow source features in the request.
Request example:
```
[{"id": 101, "src": "This is a test.", "src_feats": {"feat0": "A A A B", "feat1": "D D D F"}}]
```
It adds the `InferFeatsTransform` to the server to correctly manage features. Options from this transform can be set in the server configuration file:
```
{
"models_root": "EXPERIMENT_dummy/models",
"models": [
{
"id": 101,
"model": "model_step_1000.pt",
"timeout": 600,
"on_timeout": "to_cpu",
"load": true,
"opt": {
"gpu": 0
},
"tokenizer": {
"type": "pyonmttok",
"mode": "conservative",
"params": {
"bpe_model_path": "codes.bpe",
"joiner": "￭",
"joiner_annotate": true,
"case_markup": true,
"support_prior_joiners": true
}
},
"features": {
"reversible_tokenization": "joiner",
"prior_tokenization": false
} …
```

Modified server to allow source features

---

onmt/translate/translation_server.py

Fixed the src-feats parameter error for REST server when using CTranslate2 models per @francoishernandez instructions and guidance.  I did run the check PR request script to verify there were no breaking changes.  Code was tested with CTranslate2 models and functions as expected.

fixed src-feats parameter error for REST server and CTranslate2 models

---

docs/source/quickstart.md

typo: toy_ende -> toy-ende

---

onmt/model_builder.py
onmt/opts.py
onmt/train_single.py
onmt/utils/loss.py

I propose supporting parameter freezing of the encoder and decoder. I've implemented the feature for use in my own experiments and would like to contribute the patch in response to interest demonstrated in #1857 and https://forum.opennmt.net/t/transformer-freezing-encoder-while-training-decoder/2723
The change works by
* Conditionally setting `requires_grad` to `False` on encoder/decoder parameters as specified in the configuration options
* Overwriting the freezing options from a loaded checkpoint (this is to support the most common use of parameter freezing, which is to freeze and transfer weights between training runs to be altered or fixed, e.g. to fine-tune, in another context)
Please leave any thoughts you have as comments. I am happy to refactor to fit the conventions of the repo, …

Support encoder/decoder freezing.

---

onmt/trainer.py

Cuda OOM exception errors can be triggered not only by the backward operation but also by the forward or loss computation.
This PR discards batches that may trigger such errors.

Include wider scope in try / exception training loop

---

onmt/opts.py
onmt/translate/translator.py
tools/mbr_bleu.py
tools/oracle_bleu.py
tools/oracle_comet.py

The goal is to be able to rerank nbest hypothesis when combining the score of each translation with another score.
In the context of Noisy Channel Reranking we combine:
the score of each translation
the backward score with an inverse model
a language model score of each translation
New tools:
mbr_bleu: compute the best bleu amongst n_best hypotheses between themselves.
oracle_bleu: compute the best possible BLEU against a reference and pick the best in n_best
oracle_comet: same with unbable/comet

Flag to output the score of each sentence at inference + various scoring tools

---

docs/source/examples/Translation.md
onmt/opts.py
onmt/tests/test_beam_search.py
onmt/translate/penalties.py

When normalizing with length_penalty = avg 
BEFORE:
scores / length
AFTER
score / length ** alpha
default alpha = 1
Change doc advising to use length_penalty avg (default value in fairseq) to produce "longer" translations.

Add length penalty alpha, change docs for clarity

---

onmt/trainer.py

In the previous version of the code, validation statistics were calculated by all workers. As they are also calculated on the full dataset rather than at batch level, gathering them was unnecessary.
However, all workers did exactly the same calculation, so it can be limited to a single GPU. In this way, the valid statistics gathering becomes unnecessary for this reason as well.

validation stats are calculated by a single GPU

---

onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/modules/average_attn.py
onmt/modules/multi_headed_attn.py
onmt/utils/misc.py

Set attn_type and layer_cache as attributes of MultiHeadedAttention and AverageAttention.
Change decoder state of the layer cache from Dict to Tensors for Torch Jit compatibility.
Optimize gen_relative_positions (tensors created directly on gpu) => inference 8% faster.
Fix average_attention on fp16 (was buggy, missing cast).
NB: when activating the JIT decorators in MultiHeadedAttention, there is no gain. Inquiring why.

MHA + Average + tranformer enc/dec refac

---

onmt/inputters/text_utils.py

The translate module expects a target, which is not a standard behavior for translation, `len(new['tgt'])` is none.
https://github.com/anthdr/OpenNMT-py/blob/891b1ef08ea05a9173879d51a79cb7c52aeccd9d/onmt/inputters/text_utils.py#L16-L34
Ignoring the counting of tgt tokens in batching allows the correct behavior of this module.

ignoring tgt tokens in batching for translation

---

onmt/translate/translation_server.py

seems like the code for translator_server has changed in v3.0 but the code for Ctranslate2Translator class hasn't. since it doesn't have vocab attribute, using ctranslate2 models throws error.

onmt_server works with ctranslate2

---

onmt/bin/release_model.py
setup.py

The package was not listed as a dependency because it was not available on all platforms at first. It is now available on all the platforms where `torch` is also available.

Add CTranslate2 in requirements

---

onmt/inputters/inputter.py
onmt/opts.py
onmt/tests/test_transform.py
onmt/train_single.py
onmt/trainer.py
onmt/transforms/tokenize.py
onmt/transforms/transform.py
onmt/utils/loss.py
tools/LM_scoring.py

This PR does:
Cf: https://arxiv.org/pdf/2004.14928.pdf
Initially designed for Low Resource NMT but it gave also good results with a EN-DE experiment. Output perplexity in the target language is lower than without the LM distillation.
Also fix the set() randomness in the get_specials() transforms.
(we need the exact same vocab for the LM and NMT models)
fix #2251

LMprior (LM Distillation) with CT2 or Onmt-py to infer LM model

---

onmt/model_builder.py
onmt/opts.py
onmt/trainer.py
onmt/utils/optimizers.py

For benchmark and better documentation on performance I am adding back Apex.amp.
As a reminder, we have:
For adam:
if fp32, then it will use the native fp32 adam training.
if fp16, then it will use the "amp" library included in pytorch.
For fusedadam:
if fp16 or fp32 and "opt.apex_opt_level" is NOT set, then it will use the old legacy FusedAdam algorythm from the original apex implementation. https://github.com/NVIDIA/apex/blob/master/apex/contrib/optimizers/fp16_optimizer.py
if "opt.apex_opt_level" is set to:
"O0": training will be done in fp32 whatever the opt.model_dtype flag.
"O1" or "O2" will train according to those parameters: https://github.com/NVIDIA/apex/blob/master/docs/source/amp.rst
"O3": does not work with fusedadam, so do not use.

reinstate apex.amp (O1 O2)

---

.github/workflows/push.yml
onmt/tests/pull_request_chk.sh
onmt/tests/test_events.py
onmt/trainer.py
onmt/utils/report_manager.py

This PR is a patch for tensorboard logging failure in case where no metrics are calculated.
It includes a test to check for scalars in event files.
The validation in cpu-only mode is re-enabled and tested, as well as dynamic scoring at validation time.

Fix tensorboard logging

---

onmt/decoders/decoder.py
onmt/translate/translation.py
onmt/utils/loss.py

This PR fixed `coverage_attn` bugs which has been discussed on [https://github.com/OpenNMT/OpenNMT-py/issues/2013](https://github.com/OpenNMT/OpenNMT-py/issues/2013).
Actual codes are slightly differ from it due to considering inference(non teacher-forcing) stage. (See comment)
https://github.com/Sanghyuk-Choi/OpenNMT-py/blob/coverage_fix/onmt/decoders/decoder.py#L364-L365
I've tested the code working properly with dummy dataset as it described on the original paper.
Also, This PR includes `_build_source_tokens` on `translation.py`, since `src_raw = None` causes error when `--attn_debug = True`.

fixed coverage attention, and translator for attn_debug

---

onmt/bin/build_vocab.py
onmt/inputters/text_utils.py
onmt/trainer.py
onmt/transforms/tokenize.py
onmt/transforms/transform.py
onmt/utils/scoring_utils.py

This PR removes the `Detokenizer` class from `onmt.utils.scoring_utils`. The detokenization is now based on the `applys_reverse` method of the `TransformPipe`.

Fix detok in scoring utils

---

onmt/model_builder.py
onmt/modules/embeddings.py
onmt/opts.py
onmt/tests/test_beam_search.py
onmt/tests/test_greedy_search.py
onmt/transforms/misc.py
onmt/translate/beam_search.py
onmt/translate/decode_strategy.py
onmt/translate/greedy_search.py
onmt/translate/translator.py

This PR does 4 things:
1) Introduces a variant of Positional Encoding (fixed Sinusoidal) where SIn/Cos are concat instead of interleaved (default). This is required to load the NLLB-200 models from Fairseq Architecture.
2) Allow a change in the start decoder token (so far it was hard coded to be BOS as we do at Onmt) so that we can make it </s> which is the behavior for Fairseq's NLLB-200 models
3) Introduce a transform "suffix" which is equivalent to "prefix". This enables to add automatically a suffix to source (or target). This is required for NLLB-200 (which asks for a </s> src_lang in the source) but also allow to add a domain or such in the source.
4) Add a apply_reverse behavior to the "prefix" transform. When using a target prefix (eg: target language for NLLB-200) it will remove …

Prepare for NLLB-200 inference (and maybe finetuning)

---

docs/source/FAQ.md
onmt/transforms/uppercase.py

This transform converts source and target examples to uppercase. This is needed so the model can better learn to translate sentences in all caps. 
I use `unicodedata` to normalize the converted uppercase strings as this is needed for some languages (e.g. Greek). One issue is that the normalization removes all diacritics and accents from the uppercased strings, even though in few occasions some diacritics should be kept even in the uppercased form.

Add uppercase transform

---

onmt/inputters/dynamic_iterator.py
onmt/utils/logging.py

replace #2178 
also since dataloader is in spawn mode by default, added a hack to keep logs to stdout from spawned processes. (datasets loading cycles)

"better" log

---

README.md

The "--output" and "--model" arguments to onmt_release_model were incorrectly specified with single hyphens, which results in "unrecognized argument" errors if run verbatim.

Fixing model release example command in README

---

onmt/modules/global_attention.py

The `Linear` module of pytorch should accept arbitrary size of input tensor as long as the last dimension equals to the input dimension. So these `view` operations can be safely removed.
However I didn't test it yet, I just edit them on Github

Remove unnecessary `view` for linear operation

---

onmt/opts.py
onmt/train_single.py

This PR provides the ability to override the checkpoint's dropout settings (`dropout`, `attention_dropout`)  when finetuning a Transformer model.
A new flag `override_opts` is added. This overriding can thus be disabled with `--override_opts False` 
It is not possible at the moment because the checkpoint's `model_opts `override those set in the config.
See the following discussion about this topic:
https://forum.opennmt.net/t/tranformer-change-dropout-when-finetuning/4625

allow to override the checkpoint's droupout settings

---

docs/source/FAQ.md
docs/source/refs.bib
onmt/transforms/fuzzymatch.py
onmt/transforms/fuzzymatching.py
requirements.opt.txt
setup.py

This transform augments training examples with fuzzy matches for Neural Fuzzy Repair (https://aclanthology.org/P19-1175/). Although it works fine in my custom workflow, I'm sending this PR as draft as we need to discuss some generalization decisions (e.g. the special fuzzy token which is currently provided as a global constant and not as an option in the config) and probably add some more documentation for other important training options that must be fine-tuned in order to get good performance and minimize overhead during training (more specifically, the `-bucket_size`, `-bucket_size_init`, `-bucket_size_increment` and `-prefetch_factor` options).

Add fuzzymatching transform for Neural Fuzzy Repair

---

docs/source/FAQ.md
onmt/transforms/inlinetags.py
setup.py

One more transform that injects inline tags (placeholders) into source and target segments during training. The transform makes use of 2 kind of placeholders: paired tags ("`...｟ph_#_beg｠`... `｟ph_#_end｠...`" and standalone tags ( "...`｟ph_#_std｠`...), where `#` is the inline tag number.
The transform requires a prepared tab-delimited dictionary with source and target terms and phrases and uses an [Aho-Corasick](https://en.wikipedia.org/wiki/Aho–Corasick_algorithm) library for multi-string searches. 
2 points for discussion:
1. Due to the automatic way of numbering and adding inline tags in the vocab, they are hard-coded and not offered as an option. I guess it could be done, but I can't think of an easy and intuitive way, as the user will still be restricted to the pattern they have to …

Add inlinetags transform

---

docs/source/FAQ.md
onmt/opts.py
onmt/translate/translator.py
onmt/utils/parse.py

This PR intends to recover alignment computation between source and gold target (See issue https://github.com/OpenNMT/OpenNMT-py/issues/2310).
This functionality is essential to evaluate learnt alignements during training.
It was discarded in https://github.com/OpenNMT/OpenNMT-py/pull/1788

Recover source and gold target alignment computation

---

onmt/transforms/inlinetags.py

Fixes variable typo that resulted in wrong tag patterns in the target text.

Fix variable typo in inlinetags transform

---

onmt/transforms/inlinetags.py

Fixes a list joining issue in the inlinetags transform that prevented correct tokenization in punctuation marks.

Fix spaces before punctuation

---

onmt/models/model_saver.py
onmt/opts.py
onmt/transforms/tokenize.py
tools/lora_weights.py

* Now LoRa training will save the diff weights only in a separate checkpoint. This checkpoint contains diff LoRa weights and the optimizer state.
* added new tool to either 1) merge diff LoRa weights in the base model and save the new trained model in the same format as the base model or 2) add back the LoRa weights and optimizer states to the base model for further training.
* misc change in sentenepiece tokenization to take into account potential </s> (DefaultTokens.EOS) in the middle of sentences.

Change LoRa saving + tool to merge or retrieve model for further training

---

docs/source/FAQ.md
onmt/model_builder.py
onmt/modules/lora.py
onmt/modules/multi_headed_attn.py
onmt/opts.py
requirements.opt.txt
tools/lora_weights.py

New:
Enables 8bit compression for nn.Linear layers
=> Training can load the base model in 8bit mode and train the LoRa layers in FP16
Fixes:
Rotary embedding during training
LoRa merging (bug in MS LoRa repo)
At the moment you cannot compress a layer for which you want to finetune with LoRa.

8bit loading and LoRa fixes

---

onmt/inputters/inputter.py
onmt/transforms/docify.py
tools/convert_llama.py
tools/convert_openllama.py

adding the openllama converter. Basically it takes the checkpoint from HF hub.
added a tweak (for both llaama / openllama) which does not add the special ((newline)) when using the docify transform. the reason is that the sentencepiece transform map the ((newline)) token to '\n' = '<0x0A>' in the vocab.

add openllama converter.

---

docs/source/index.rst

The path of the tutorial in the index was not aligned with the final file path that was merged.
This commit fixes it.
Though, to fix the deployed docs, we need to either:
- trigger a new release (easy but very dirty);
- push a locally built version with the fix on the gh-pages branch (quite easy and a bit less dirty);
- take this opportunity to separate the docs build in the workflow, to allow rebuilding docs without necessarily triggering a release (a bit more time consuming).

Fix vicuna tutorial path in doc index

---

onmt/transforms/inlinetags.py

Corpus ratio now is finally applied correctly. As it seems, the only way to have an accurate ratio is to pass every single example through the augmentation function and then propagate a boolean with each example that denotes if that example has actually been augmented with tags.

Fix corpus ratio for inlinetags transform

---

onmt/decoders/transformer.py
onmt/modules/multi_headed_attn.py

closes #2331 
My first test:
very small improvement in terms of speed (2-3 %)
when finetuning llama, save 1.5GB out of 19.5GB in gpu ram
at inference, same vRam usage, almost same speed.
2GB saved when increasing the batch size + sequence length.

Flash attention

---

docs/source/FAQ.md
onmt/transforms/terminology.py
requirements.opt.txt
setup.py

This is a transform for augmenting source examples with terms so the model can adapt at inference with user-provided terms.
Similar to the `inlinetags` transform, it requires a user-prepared dictionary with source-target entries, it uses the `pyahocorasick` lib for fast multi-string searches, and it brings a new, and hefty, dependency, `spacy`. Spacy is used for lemmatization as this transform works with lemmas in order to a) solve the word inflection problem when searching for terms in any form, and b) make the model inflect correctly most target terms at inference.

Add terminology transform

---

onmt/transforms/inlinetags.py

- Fixes a bug where all examples were wrongly passed to the augmentation algorithm.  
- Skip searching half examples to greatly improve performance (this sets a hard limit of `0.5` to the `tags_corpus_ratio` which is excessive and must be avoided anyway).

Fix ratio bug and improve performance in inlinetags transform

---

onmt/translate/translator.py

This addresses the following error when running translator with `report_align=true`
Traceback 
```
File "/usr/local/lib64/python3.8/site-packages/onmt/translate/translator.py", line 422, in _translate
n_best_preds_align = [" ".join(align) for align in align_pharaohs]
File "/usr/local/lib64/python3.8/site-packages/onmt/translate/translator.py", line 422, in <listcomp>
n_best_preds_align = [" ".join(align) for align in align_pharaohs]
TypeError: sequence item 0: expected str instance, list found
```
Caused by change to `build_align_pharaoh` where it now returns `return align_pairs, align_scores` versus previous `return align_pairs`

Fix alignment generation error

---

onmt/inputters/dynamic_iterator.py
onmt/inputters/text_utils.py

the sorting based on max length is less efficient than key=src, tgt

revert batching mode

---

.github/workflows/push.yml
data/data_lm/gen-nucleus-sampling-sol2.txt
data/data_lm/gen-sampling-beams-sol2.txt
onmt/bin/translate.py
onmt/decoders/transformer.py
onmt/encoders/mean_encoder.py
onmt/encoders/transformer.py
onmt/inference_engine.py
onmt/inputters/dynamic_iterator.py
onmt/inputters/text_corpus.py
onmt/inputters/text_utils.py
onmt/model_builder.py
onmt/modules/copy_generator.py
onmt/modules/global_attention.py
onmt/modules/multi_headed_attn.py
onmt/tests/pull_request_chk.sh
onmt/trainer.py
onmt/transforms/docify.py
onmt/transforms/transform.py
onmt/translate/beam_search.py
onmt/translate/translation.py
onmt/translate/translator.py
onmt/utils/misc.py
tools/LM_scoring.py

This PR has the following purposes:
- get rid of the old batch["indices"] key which was not actually used.
- introduce the following keys
batch["cid"]: identify the corpus id of the example
batch["cid_line_number"]: identify the corpus id line number
these two keys will be helpful to retrieve the lines where a training stopped and resume training at those lines
one other key:
batch["ind_in_bucket"] de facto replaces the "indices" but represents the index in the current bucket
This PR hence will sort buckets ALSO at inference (was doing it at training) which will speed up the inference and then after translation we reorder the translations from these "ind_in_bucket".

New indexing

---

onmt/opts.py
onmt/translate/translator.py

This introduces a max length per batch at inference.
By default the max_length was set at 250 tokens.
It is now Min(max_length, batch_max_len * max_length_ratio) + 5
Let say the max_length_ratio is set at 1.25 (large enough for most European languages)
If a batch has examples from length 5 to 10
the max_length will be = 10 x 1.25 + 5 = 17
The "5" offset prevents from stopping to early for very short sequences and the max_length_ratio enable to stop before the max_length (which might be too high) and prevent from hallucinations / repetitions.
If you need to disable the feature, set it to zero.

Set dynamic max length per batch

---

onmt/modules/bnb_linear.py
requirements.opt.txt

prior to bnb < 0.40.0 the device could not be passed to the original Linear4bit() preventing from using skip_init()
Now it's implemented, so removing the copy-paste / modified version of Linear4bit (and 8bit).

update to skipinit weights with bnb

---

onmt/decoders/transformer.py
onmt/model_builder.py
onmt/modules/bnb_linear.py
onmt/modules/moe.py
onmt/opts.py

Inference for now.
Finetuning would require to add the auxiliary loss to balance the experts at training.

MoE for mixtral 8x7b

---

onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/model_builder.py
onmt/modules/moe.py
onmt/modules/multi_headed_attn.py
onmt/modules/position_ffn.py
onmt/modules/rmsnorm.py
onmt/opts.py
onmt/translate/translator.py
onmt/utils/distributed.py
tools/convert_HF_llamalike.py

This PR does:
1) switch apex RMSNorm to awq_inference_engine RMSNorm which is much faster
2) add rotary_theta as an option (llama/mistral used to use 1e4 while Mixtral and mistralv0.2 use 1e6)
3) use flash2 flash_attn_with_kvcache instead of regular flash_attn_func for step > 0 (much faster to increment cache in place in certain cases)

use flash_attn_with_kvcache for faster inference

---

onmt/modules/multi_headed_attn.py

Revert changes inserted by #2538 and adapt to  #2539.

Restored masked scaled dot attention

---

onmt/decoders/transformer.py
onmt/encoders/transformer.py
onmt/model_builder.py
onmt/modules/multi_headed_attn.py
onmt/opts.py
onmt/translate/translator.py
tools/convert_HF.py

Just a note on this PR to remember. Phi-2 from MSFT uses a rotary dim (32) which is different from the dim per head (2560/32=80) which makes things a lit bit awkward, rotary embeddings are applied only to the first 32 dimensions and beyond (from 33 to 80) it's just a plain copy.
NOTE 2: I am trying to build a generic converter convert_HF.py fo now compatible with Llama, Mistral, Phi, hope to include other filters and in the end have only a single converter.

Support for Microsoft's Phi-2 model

---

eval_llm/MMLU/run_mmlu_opennmt.py
eval_llm/WIKITEXT2/run_wikitext-2_benchmark.py
onmt/decoders/ensemble.py
onmt/inputters/text_corpus.py
onmt/inputters/text_utils.py
onmt/transforms/fuzzymatch.py
onmt/transforms/inlinetags.py
onmt/transforms/misc.py
onmt/transforms/normalize.py
onmt/transforms/terminology.py
onmt/transforms/tokenize.py
onmt/transforms/uppercase.py
onmt/translate/translation_server.py
onmt/utils/alignment.py
tools/convert_HF.py

fix ensemble decoding when using flash-attn
fix "\n" tokenization (they were stripped out) leading to lower MMLU scores
patch to tokenize "\n\n" into"\n" "\n" when using gpt2 BPE
adapt phi-2 converter to the new layer names

misc + fix "\n" tokenization + phi-2 new layer names

---

onmt/tests/test_transform.py
onmt/transforms/insert_mask_before_placeholder.py

This PR enables multiple "response patterns" in LLM-like training examples (with prompt and response) for  multi-task finetuning.

Allow multiple response patterns in the insert_mask_before_placeholder transform

---

onmt/trainer.py

This PR applies the same logic to valid batches as to train batches when the zero-out-prompt-loss mechanism is activated.

Fix valid stats when we zero-out the prompt-loss

---

onmt/modules/multi_headed_attn.py

This PR proposes a fix for the flash attention path in the multi-head attention module.
The flash attention block doesn't support the left padding mask, so we apply it upstream.
https://github.com/Dao-AILab/flash-attention/issues/649
We apply  the `key_pad_mask` to the values contained in the KV-cache at the first step only, for all scenari (standard, flash, sdpa mechanisms).

fixed masked flash attention
